In [134]:
import json
import re
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd

In [ ]:
labels_path = Path("./yes_1.xlsx")
df = pd.read_excel(labels_path)

In [136]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Страница 1,...,Unnamed: 310,Unnamed: 311,Unnamed: 312,Unnamed: 313,Unnamed: 314,Unnamed: 315,Unnamed: 316,Страница 56,Unnamed: 318,Страница 57
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.1 Площадь штриховки (Одиночный выбор),14.2 Нажим (Одиночный выбор),Шея отделена от тела линией (Одиночный выбор)
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Заштрихованное облако/4,Пейзаж/5,Пейзаж преобладает над изображением человека/6,Дождь,Солнце,Земля,Другое,NaN,NaN,NaN
2,ID ответа,Дата ответа,Затраченное время,Источник ответа,Источник ответа,Респондент,IP-hash,UA-hash,Логин,Код,...,249,250,251,252,1058,1059,1060,1062,1063,253
3,1211956,2025.07.25 14:19,00:06:21,Доп. ссылка,Доп. ссылка: Трифонова Виктория Вадимовна,NaN,127.0.0.1,127.0.0.1,NaN,САМ2_13лм7кл_49,...,NaN,NaN,NaN,NaN,NaN,Земля,NaN,NaN,NaN,Просто линия
4,1211954,2025.07.25 10:54,00:07:29,Доп. ссылка,Доп. ссылка: Коваль Оксана Владимировна,NaN,127.0.0.1,127.0.0.1,NaN,САМ2_7лм2кл_5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7001,1142510,2025.03.28 19:29,00:15:20,Доп. ссылка,Доп. ссылка: Мосенцова Анна Олеговна,NaN,127.0.0.1,127.0.0.1,NaN,ЧУВ5лждс (76),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
7002,1142503,2025.03.28 19:12,00:31:32,Доп. ссылка,Доп. ссылка: Мосенцова Анна Олеговна,NaN,127.0.0.1,127.0.0.1,NaN,ЧУВ5лждс (75),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
7003,1133195,2025.03.24 21:22,00:10:04,Доп. ссылка,Доп. ссылка: Клопотова Екатерина Евгеньевна.,NaN,127.0.0.1,127.0.0.1,NaN,ЧУВ6лмдс,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
7004,1113127,2025.02.18 17:04,02:29:39,Доп. ссылка,Доп. ссылка: Web-ссылка,NaN,127.0.0.1,127.0.0.1,NaN,1,...,NaN,Пейзаж/5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Галстук
7005,1112948,2025.02.17 14:09,00:24:22,Доп. ссылка,Доп. ссылка: Web-ссылка,NaN,127.0.0.1,127.0.0.1,NaN,1,...,NaN,NaN,NaN,NaN,Солнце,NaN,NaN,NaN,NaN,Бусы

In [137]:
df.shape

(7006, 320)

In [138]:
df.columns.to_list()

['Unnamed: 0',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Страница 1',
 'Страница 2',
 'Страница 3',
 'Страница 5',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Страница 6',
 'Страница 7',
 'Страница 8',
 'Страница 9',
 'Страница 10',
 'Страница 11',
 'Страница 12',
 'Страница 13',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Страница 14',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 'Unnamed: 49',
 'Unnamed: 50',
 'Unnamed: 51',
 'Страница 15',
 'Страница 16',
 'Unnamed: 54',
 'Unnamed: 55',
 'Unnamed: 56',
 'Unnamed: 57',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60',
 'Unnamed: 61',
 'Unnamed: 62',
 'Unnamed: 63',
 'Страница 17',
 'Страница 18',
 'Страница 19',
 'Страница 20',
 'Unnamed: 68',
 'Unnamed: 69',
 'Unnamed: 70',
 'Страница 21',
 'Страница 23',
 'Unnamed: 73',
 'Unnamed: 74',
 'Unnamed: 75',
 'Unnamed: 76',
 'Unnamed: 77',
 'Страница 24',
 'Unnamed: 79',
 'Unnamed: 80',
 'Unnamed: 81',
 'Unnamed: 82',
 'Unnamed: 83',
 'Unnamed: 84',
 'Unnamed: 85',
 'Страница 25',
 'Unnamed: 87',
 'Unnamed: 88',
 'Unnamed: 89',
 'Unnamed: 90',
 'Unnamed: 91',
 'Unnamed: 92',
 'Unnamed: 93',
 'Unnamed: 94',
 'Unnamed: 95',
 'Unnamed: 96',
 'Unnamed: 97',
 'Unnamed: 98',
 'Unnamed: 99',
 'Unnamed: 100',
 'Unnamed: 101',
 'Unnamed: 102',
 'Unnamed: 103',
 'Unnamed: 104',
 'Unnamed: 105',
 'Unnamed: 106',
 'Unnamed: 107',
 'Unnamed: 108',
 'Unnamed: 109',
 'Unnamed: 110',
 'Unnamed: 111',
 'Unnamed: 112',
 'Unnamed: 113',
 'Unnamed: 114',
 'Unnamed: 115',
 'Unnamed: 116',
 'Unnamed: 117',
 'Unnamed: 118',
 'Unnamed: 119',
 'Unnamed: 120',
 'Unnamed: 121',
 'Unnamed: 122',
 'Unnamed: 123',
 'Unnamed: 124',
 'Unnamed: 125',
 'Unnamed: 126',
 'Unnamed: 127',
 'Unnamed: 128',
 'Unnamed: 129',
 'Unnamed: 130',
 'Unnamed: 131',
 'Unnamed: 132',
 'Unnamed: 133',
 'Unnamed: 134',
 'Unnamed: 135',
 'Unnamed: 136',
 'Unnamed: 137',
 'Unnamed: 138',
 'Страница 26',
 'Unnamed: 140',
 'Unnamed: 141',
 'Unnamed: 142',
 'Unnamed: 143',
 'Страница 27',
 '!!!',
 'Unnamed: 146',
 'Unnamed: 147',
 'Unnamed: 148',
 'Страница 28',
 'Unnamed: 150',
 'Unnamed: 151',
 'Unnamed: 152',
 'Unnamed: 153',
 'Unnamed: 154',
 'Unnamed: 155',
 'Unnamed: 156',
 'Unnamed: 157',
 'Unnamed: 158',
 'Unnamed: 159',
 'Unnamed: 160',
 'Unnamed: 161',
 'Unnamed: 162',
 'Unnamed: 163',
 'Unnamed: 164',
 'Unnamed: 165',
 'Unnamed: 166',
 'Unnamed: 167',
 'Unnamed: 168',
 'Unnamed: 169',
 'Unnamed: 170',
 'Unnamed: 171',
 'Unnamed: 172',
 'Страница 29',
 'Страница 30',
 'Unnamed: 175',
 'Unnamed: 176',
 'Unnamed: 177',
 'Unnamed: 178',
 'Unnamed: 179',
 'Unnamed: 180',
 'Страница 31',
 'Unnamed: 182',
 'Unnamed: 183',
 'Unnamed: 184',
 'Unnamed: 185',
 'Unnamed: 186',
 'Unnamed: 187',
 'Страница 32',
 'Страница 33',
 'Страница 34',
 'Страница 35',
 'Страница 36',
 'Unnamed: 193',
 'Unnamed: 194',
 'Unnamed: 195',
 'Unnamed: 196',
 'Unnamed: 197',
 'Unnamed: 198',
 'Страница 37',
 'Unnamed: 200',
 'Unnamed: 201',
 'Unnamed: 202',
 'Unnamed: 203',
 'Unnamed: 204',
 'Страница 38',
 'Unnamed: 206',
 'Unnamed: 207',
 'Unnamed: 208',
 'Unnamed: 209',
 'Unnamed: 210',
 'Страница 39',
 'Unnamed: 212',
 'Unnamed: 213',
 'Unnamed: 214',
 'Unnamed: 215',
 'Unnamed: 216',
 'Страница 40',
 'Unnamed: 218',
 'Unnamed: 219',
 'Unnamed: 220',
 'Unnamed: 221',
 'Страница 41',
 'Unnamed: 223',
 'Unnamed: 224',
 'Unnamed: 225',
 'Unnamed: 226',
 'Страница 42',
 'Unnamed: 228',
 'Unnamed: 229',
 'Unnamed: 230',
 'Unnamed: 231',
 'Unnamed: 232',
 'Страница 43',
 'Unnamed: 234',
 'Unnamed: 235',
 'Unnamed: 236',
 'Unnamed: 237',
 'Unnamed: 238',
 'Страница 44',
 'Unnamed: 240',
 'Unnamed: 241',
 'Unnamed: 242',
 'Unnamed: 243',
 'Unnamed: 244',
 'Страница 45',
 'Unnamed: 246',
 'Unnamed: 247',
 'Unnamed: 248',
 'Unnamed: 249',
 'Unnamed: 250',
 'Страница 46',
 'Unnamed: 252',
 'Unnamed: 253',
 'Unnamed: 254',
 'Unnamed: 255',
 'Unnamed: 256',
 'Unnamed: 257',
 'Страница 47',
 'Unnamed: 259',
 'Unnamed: 260',
 'Unnamed: 261',
 'Unnamed: 262',
 'Unnamed: 263',
 'Unnamed: 264',
 'Страница 48',
 'Unnamed: 266',
 'Unnamed: 267',
 'Unnamed: 268',
 'Unnamed: 269',
 'Unnamed: 270',
 'Unnamed: 271',
 'Unnamed: 272',
 'Unnamed: 273',
 'Страница 49',
 'Unnamed: 275',
 'Unnamed: 276',
 'Unnamed: 277',
 'Unnamed: 278',
 'Unnamed: 279',
 'Страница 50',
 'Unnamed: 281',
 'Unnamed: 282',
 'Unnamed: 283',
 'Unnamed: 284',
 'Страница 51',
 'Unnamed: 286',
 'Unnamed: 287',
 'Unnamed: 288',
 'Unnamed: 289',
 'Unnamed: 290',
 'Unnamed: 291',
 'Unnamed: 292',
 'Страница 52',
 'Страница 53',
 'Страница 54',
 'Unnamed: 296',
 'Unnamed: 297',
 'Unnamed: 298',
 'Unnamed: 299',
 'Unnamed: 300',
 'Unnamed: 301',
 'Unnamed: 302',
 'Unnamed: 303',
 'Unnamed: 304',
 'Unnamed: 305',
 'Unnamed: 306',
 'Страница 55',
 'Unnamed: 308',
 'Unnamed: 309',
 'Unnamed: 310',
 'Unnamed: 311',
 'Unnamed: 312',
 'Unnamed: 313',
 'Unnamed: 314',
 'Unnamed: 315',
 'Unnamed: 316',
 'Страница 56',
 'Unnamed: 318',
 'Страница 57']

In [139]:
# Удаляем ненужные колонки

columns_to_drop = [
    df["ID ответа"].name,
    df["Дата ответа"].name,
    df["Затраченное время"].name,
    df["Источник ответа"].name,
    df["Источник ответа.1"].name,
    df["Респондент"].name,
    df["IP-hash"].name,
    df["UA-hash"].name,
    df["Логин"].name,
]

df.drop(columns=columns_to_drop, inplace=True)
df

Exception ignored in: <function ZipFile.__del__ at 0x000002061EF84AF0>
Traceback (most recent call last):
  File "d:\Conda\CondaEnvs\diploma-env\lib\zipfile.py", line 1847, in __del__
    self.close()
  File "d:\Conda\CondaEnvs\diploma-env\lib\zipfile.py", line 1864, in close
    self.fp.seek(self.start_dir)
ValueError: seek of closed file

KeyError: 'ID ответа'

In [ ]:
df.iloc[0]

Страница 1      Укажите код-идентификатор обследуемого (Свобод...
Страница 2         Укажите возраст обследуемого (Свободный ответ)
Страница 3             Укажите пол обследуемого (Одиночный выбор)
Страница 5         1 Расположение на листе  (Множественный выбор)
Unnamed: 13                                                   NaN
                                      ...
Unnamed: 315                                                  NaN
Unnamed: 316                                                  NaN
Страница 56              14.1 Площадь штриховки (Одиночный выбор)
Unnamed: 318                         14.2 Нажим (Одиночный выбор)
Страница 57         Шея отделена от тела линией (Одиночный выбор)
Name: 0, Length: 311, dtype: object

In [ ]:
df.iloc[0].to_list()

['Укажите код-идентификатор обследуемого (Свободный ответ)',
 'Укажите возраст обследуемого (Свободный ответ)',
 'Укажите пол обследуемого (Одиночный выбор)',
 '1 Расположение на листе\xa0 (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '1.2 Степень смещения вправо (Одиночный выбор)',
 '1.3 Степень смещения влево (Одиночный выбор)',
 '1.4 Степень смещения вверх (Одиночный выбор)',
 '1.5 Степень смещения вниз (Одиночный выбор)',
 '1.6\xa0Размещение в углу (Одиночный выбор)',
 '1.7\xa0Что обрезано (Множественный выбор)',
 nan,
 nan,
 nan,
 '2.\xa0Размер рисунка (Одиночный выбор)',
 '3.\xa0Ракурс (Одиночный выбор)',
 'Поза (Одиночный выбор)',
 '4. Фигура в движении (Одиночный выбор)',
 '5.\xa0Способ изображения (Одиночный выбор)',
 '6.\xa0Изображение персонажа (Одиночный выбор)',
 '6.1\xa0Персонаж (Одиночный выбор)',
 '7.\xa0Нажим (Множественный выбор)',
 nan,
 nan,
 nan,
 '8. Особенности линии (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '8.2\xa0Множественные, степень выраженности (Одиночный выбор)',
 '8.3\xa0Эскизные, степень выраженности (Одиночный выбор)',
 '8.4. "Кусочные", степень выраженности (Одиночный выбор)',
 '8.5. Недоведенные, степень выраженности (Одиночный выбор)',
 '8.6. "Промахивающиеся", степень выраженности (Одиночный выбор)',
 '9. Аккуратность рисунка (Одиночный выбор)',
 '10. Штриховка (Одиночный выбор)',
 '10.1.1. Нажим штриховки (Множественный выбор)',
 nan,
 nan,
 nan,
 '10.1.2. Аккуратность штриховки (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '11. Детализированность (Одиночный выбор)',
 '12 Стирания, исправления (Одиночный выбор)',
 '13. Устойчивость\xa0изображенного человека (Одиночный выбор)',
 '14. Грубые нарушения рисунка (Множественный выбор)',
 nan,
 nan,
 nan,
 'Изображение в рамке (Одиночный выбор)',
 '1. Голова (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '2. Детали (лицо) (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2.1 Два глаза одинаковые (Одиночный выбор)',
 '2.1.1 Форма глаз (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2.1.2 Форма левого\xa0 глаза (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2.1.3 Форма правого глаза (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2.1.4 Размер глаз (Одиночный выбор)',
 '2.1.5 Размер левого глаза (Одиночный выбор)',
 '2.1.6 Размер правого глаза (Одиночный выбор)',
 '2.1.7 Дополнительные особенности глаз (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2.1.8 Дополнительные особенности правого глаза (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2.1.9 Дополнительные особенности левого глаза (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2.1.10 Ресницы (Одиночный выбор)',
 '2.2. Нос (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 '2.3.1 Рот (Одиночный выбор)',
 '2.3.2 Форма рта (Одиночный выбор)',
 '2.3.3 Положение рта/губ (Одиночный выбор)',
 '2.3.4 Зубы (Одиночный выбор)',
 '2.3.4 Язык (Одиночный выбор)',
 '2.4. Уши (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 '2.5. Лоб (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2.6. Волосы или шапка (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 '2.7. Дополнительные детали на лице (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '3 Руки\xa0(одна или обе) (Одиночный выбор)',
 '3.1.1. Положение рук (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '3.1.2. Положение рук (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '3.2.1. Положение правой руки (Одиночный выбор)',
 '3.2.2. Положение правой руки (Одиночный выбор)',
 '3.2.3. Положение левой руки (Одиночный выбор)',
 '3.2.4. Положение левой руки (Одиночный выбор)',
 '3.3.1. Положение руки (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '3.3.2. Положение руки (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '4. Кисть (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '5. Ладонь, пальцы (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '5.1. Пальцы (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 '6. Ноги (одна или обе) (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 '6.1 Ноги\xa0 (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '6.2.1. Правая нога (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '6.2.2. Левая нога (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '6.3. Нога (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '7. Ступни (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '8. Шея (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '9. Тело (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '10. Пол (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '11. Одежда (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 '12. Дополнительные детали изображения фигуры (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '12.2. Пуговицы (Одиночный выбор)',
 '12.6. Украшения, узор на одежде (Одиночный выбор)',
 '13. Дополнительно (в руке или рядом) (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '14. Фон (Множественный выбор)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '14.1 Площадь штриховки (Одиночный выбор)',
 '14.2 Нажим (Одиночный выбор)',
 'Шея отделена от тела линией (Одиночный выбор)']

In [ ]:
# Удаляем первую строку

df.columns = df.iloc[0]
df = df.iloc[1:].reset_index(drop=True)
df

,Укажите код-идентификатор обследуемого (Свободный ответ),Укажите возраст обследуемого (Свободный ответ),Укажите пол обследуемого (Одиночный выбор),1 Расположение на листе (Множественный выбор),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.1 Площадь штриховки (Одиночный выбор),14.2 Нажим (Одиночный выбор),Шея отделена от тела линией (Одиночный выбор)
0,NaN,NaN,NaN,Без особенностей/1,Смещение вправо/2,Смещение влево/3,Смещение вверх/4,Смещение вниз/5,Размещение в углу/6,Изображение обрезано - есть место для дорисовк...,...,Заштрихованное облако/4,Пейзаж/5,Пейзаж преобладает над изображением человека/6,Дождь,Солнце,Земля,Другое,NaN,NaN,NaN
1,Код,Возраст,Пол,1,2,3,4,5,6,7,...,249,250,251,252,1058,1059,1060,1062,1063,253
2,ЧУВ6лм1кл_6,6,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
3,ЧУВ6лм1кл_5,6,мужской,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
4,ЧУВ6лм1кл_4,6,мужской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8579,ЧУВ5лждс (76),5,женский,Без особенностей/1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8580,ЧУВ5лждс (75),5,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
8581,ЧУВ6лмдс,6,мужской,NaN,NaN,NaN,Смещение вверх/4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8582,1,1,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,Пейзаж/5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Галстук
8583,1,1,женский,NaN,NaN,NaN,NaN,NaN,Размещение в углу/6,NaN,...,NaN,NaN,NaN,NaN,Солнце,NaN,NaN,NaN,NaN,Бусы

In [ ]:
for col, val in df.iloc[0].items():
    print(f"col={repr(col)} | val={repr(val)}")

col='Укажите код-идентификатор обследуемого (Свободный ответ)' | val=nan
col='Укажите возраст обследуемого (Свободный ответ)' | val=nan
col='Укажите пол обследуемого (Одиночный выбор)' | val=nan
col='1 Расположение на листе\xa0 (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Смещение вправо/2'
col=nan | val='Смещение влево/3'
col=nan | val='Смещение вверх/4'
col=nan | val='Смещение вниз/5'
col=nan | val='Размещение в углу/6'
col=nan | val='Изображение обрезано - есть место для дорисовки, но не дорисовано'
col=nan | val='Изоброжение обрезано - обрезан краем листа/ нет места для дорисовки'
col='1.2 Степень смещения вправо (Одиночный выбор)' | val=nan
col='1.3 Степень смещения влево (Одиночный выбор)' | val=nan
col='1.4 Степень смещения вверх (Одиночный выбор)' | val=nan
col='1.5 Степень смещения вниз (Одиночный выбор)' | val=nan
col='1.6\xa0Размещение в углу (Одиночный выбор)' | val=nan
col='1.7\xa0Что обрезано (Множественный выбор)' | val='голова/1'
col=nan | val='одна рука/2'
col=nan | val='обе руки/3'
col=nan | val='ноги/4'
col='2.\xa0Размер рисунка (Одиночный выбор)' | val=nan
col='3.\xa0Ракурс (Одиночный выбор)' | val=nan
col='Поза (Одиночный выбор)' | val=nan
col='4. Фигура в движении (Одиночный выбор)' | val=nan
col='5.\xa0Способ изображения (Одиночный выбор)' | val=nan
col='6.\xa0Изображение персонажа (Одиночный выбор)' | val=nan
col='6.1\xa0Персонаж (Одиночный выбор)' | val=nan
col='7.\xa0Нажим (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Слабый/2'
col=nan | val='Сильный/3'
col=nan | val='Сильно варьирует/4'
col='8. Особенности линии (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Множественные/2'
col=nan | val='Эскизные/3'
col=nan | val='"Кусочные"/4'
col=nan | val='Недоведенные/5'
col=nan | val='"Промахивающиеся"/6'
col=nan | val='Другое'
col='8.2\xa0Множественные, степень выраженности (Одиночный выбор)' | val=nan
col='8.3\xa0Эскизные, степень выраженности (Одиночный выбор)' | val=nan
col='8.4. "Кусочные", степень выраженности (Одиночный выбор)' | val=nan
col='8.5. Недоведенные, степень выраженности (Одиночный выбор)' | val=nan
col='8.6. "Промахивающиеся", степень выраженности (Одиночный выбор)' | val=nan
col='9. Аккуратность рисунка (Одиночный выбор)' | val=nan
col='10. Штриховка (Одиночный выбор)' | val=nan
col='10.1.1. Нажим штриховки (Множественный выбор)' | val='без особенностей/1'
col=nan | val='слабый/2'
col=nan | val='сильный/3'
col=nan | val='варьирует/4'
col='10.1.2. Аккуратность штриховки (Множественный выбор)' | val='Очень низкая/1'
col=nan | val='Низкая/2'
col=nan | val='Средняя (стандарт)/3'
col=nan | val='Высокая/4'
col=nan | val='Очень высокая/5'
col=nan | val='Разные виды штриховок'
col='11. Детализированность (Одиночный выбор)' | val=nan
col='12 Стирания, исправления (Одиночный выбор)' | val=nan
col='13. Устойчивость\xa0изображенного человека (Одиночный выбор)' | val=nan
col='14. Грубые нарушения рисунка (Множественный выбор)' | val='Отсутствуют/1'
col=nan | val='Отклонение от вертикали/2'
col=nan | val='Нарушение пропорций/3'
col=nan | val='Грубая асимметрия/4'
col='Изображение в рамке (Одиночный выбор)' | val=nan
col='1. Голова (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Маленькая/2'
col=nan | val='Большая/3'
col=nan | val='Искажена форма/4'
col=nan | val='Зачерненная/заштрихованная'
col=nan | val='Отсутствует/6'
col='2. Детали (лицо) (Множественный выбор)' | val='Глаза (один или оба)/1'
col=nan | val='Нос/2'
col=nan | val='Рот/3'
col=nan | val='Уши/4'
col=nan | val='Лоб/5'
col=nan | val='Волосы (шапка)/6'
col=nan | val='Другое/7'
col=nan | val='Отсутствуют все указанные выше пункты'
col='2.1 Два глаза одинаковые (Одиночный выбор)' | val=nan
col='2.1.1 Форма глаз (Множественный выбор)' | val='Точка/1'
col=nan | val='Черточка/2'
col=nan | val='Круг/3'
col=nan | val='Овал, реалистичная форма/4'
col=nan | val='«Мультяшные»/5'
col=nan | val='Форма искажена/6'
col=nan | val='Отсутствуют/7 => 2.2'
col='2.1.2 Форма левого\xa0 глаза (Множественный выбор)' | val='Точка/1'
col=nan | val='Черточка/2'
col=nan | val='Круг/3'
col=nan | val='Овал, реалистичная форма/4'
col=nan | val='«Мультяшные»/5'
col=nan | val='Форма искажена/6'
col=nan | val='Отсутствует/7 => 2.2'
col='2.1.3 Форма правого глаза (Множественный выбор)' | val='Точка/1'
col=nan | val='Черточка/2'
col=nan | val='Круг/3'
col=nan | val='Овал, реалистичная форма/4'
col=nan | val='«Мультяшные»/5'
col=nan | val='Форма искажена/6'
col=nan | val='Отсутствует/7 => 2.2'
col='2.1.4 Размер глаз (Одиночный выбор)' | val=nan
col='2.1.5 Размер левого глаза (Одиночный выбор)' | val=nan
col='2.1.6 Размер правого глаза (Одиночный выбор)' | val=nan
col='2.1.7 Дополнительные особенности глаз (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Подчеркнутый контур/2'
col=nan | val='«Пустые»/3'
col=nan | val='Зачернена радужка или весь глаз/4'
col=nan | val='Один или оба глаза закрыты волосами или шапкой/5'
col=nan | val='Изображены очки (прозрачные)/6'
col=nan | val='Изображены темные очки/7'
col=nan | val='Закрыты'
col=nan | val='Полузакрыты (прищур)'
col='2.1.8 Дополнительные особенности правого глаза (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Подчеркнутый контур/2'
col=nan | val='«Пустые»/3'
col=nan | val='Зачернена радужка или весь глаз/4'
col=nan | val='Закрыт волосами или шапкой/5'
col=nan | val='Изображены очки (прозрачные)/6'
col=nan | val='Изображены темные очки/7'
col=nan | val='Закрыт '
col=nan | val='Полузакрыт (прищур)'
col='2.1.9 Дополнительные особенности левого глаза (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Подчеркнутый контур/2'
col=nan | val='«Пустые»/3'
col=nan | val='Зачернена радужка или весь глаз/4'
col=nan | val='Закрыт волосами или шапкой/5'
col=nan | val='Изображены очки (прозрачные)/6'
col=nan | val='Изображены темные очки/7'
col=nan | val='Закрыт '
col=nan | val='Полузакрыт (прищур)'
col='2.1.10 Ресницы (Одиночный выбор)' | val=nan
col='2.2. Нос (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Увеличен размер/2'
col=nan | val='Усилен нажим/3'
col=nan | val='Другое/4'
col=nan | val='Отсутствует/5'
col='2.3.1 Рот (Одиночный выбор)' | val=nan
col='2.3.2 Форма рта (Одиночный выбор)' | val=nan
col='2.3.3 Положение рта/губ (Одиночный выбор)' | val=nan
col='2.3.4 Зубы (Одиночный выбор)' | val=nan
col='2.3.4 Язык (Одиночный выбор)' | val=nan
col='2.4. Уши (Множественный выбор)' | val='Без особенностей/2'
col=nan | val='Усилен нажим/3'
col=nan | val='Преувеличен размер/4'
col=nan | val='Другое/5'
col=nan | val='Отсутствуют/1'
col='2.5. Лоб (Множественный выбор)' | val='Маленький /2'
col=nan | val='Средний (стандарт)/3'
col=nan | val='Большой/4'
col=nan | val='Скрыт волосами или шапкой/5'
col=nan | val='Скрыт волосами, усилен нажим/6'
col=nan | val='Другое/7'
col=nan | val='Отсутствует/1'
col='2.6. Волосы или шапка (Множественный выбор)' | val='Без особенностей/2'
col=nan | val='Нарисованы небрежно/3'
col=nan | val='Нарисованы особо старательно/4'
col=nan | val='Другое/5'
col=nan | val='Отсутствуют/1'
col='2.7. Дополнительные детали на лице (Множественный выбор)' | val='Брови/2'
col=nan | val='Усы и/или борода/3'
col=nan | val='Морщины/4'
col=nan | val='Маска'
col=nan | val='Рисунки на лице'
col=nan | val='Другое/5'
col=nan | val='Отсутствуют/1'
col='3 Руки\xa0(одна или обе) (Одиночный выбор)' | val=nan
col='3.1.1. Положение рук (Множественный выбор)' | val='Слегка отставлены (стандарт)/1'
col=nan | val='Прижаты к телу (от верха до локтя)/2'
col=nan | val='Свободно опущены/3'
col=nan | val='Сильно отставлены/4'
col=nan | val='Вытянуты в стороны или вперед/5'
col=nan | val='Подняты/6'
col=nan | val='Дополнительно/7'
col='3.1.2. Положение рук (Множественный выбор)' | val='За спиной или в карманах/1'
col=nan | val='На фоне тела/2'
col=nan | val='Скрещены на груди/3'
col=nan | val='Уперты в бока/4'
col=nan | val='Закрывают генитальную область/5'
col=nan | val='Прижаты к голове/6'
col=nan | val='Другое'
col='3.2.1. Положение правой руки (Одиночный выбор)' | val=nan
col='3.2.2. Положение правой руки (Одиночный выбор)' | val=nan
col='3.2.3. Положение левой руки (Одиночный выбор)' | val=nan
col='3.2.4. Положение левой руки (Одиночный выбор)' | val=nan
col='3.3.1. Положение руки (Множественный выбор)' | val='Слегка отставлена (стандарт)/1'
col=nan | val='Прижата к телу (от верха до локтя)/2'
col=nan | val='Свободно опущена/3'
col=nan | val='Сильно отставлена/4'
col=nan | val='Вытянута в сторону или вперед/5'
col=nan | val='Поднята/6'
col=nan | val='Дополнительно/7'
col='3.3.2. Положение руки (Множественный выбор)' | val='За спиной или в кармане/1'
col=nan | val='На фоне тела/2'
col=nan | val='Уперта в бок/3'
col=nan | val='Закрывает генитальную область/4'
col=nan | val='Прижата к голове/5'
col=nan | val='Другое'
col='4. Кисть (Множественный выбор)' | val='Маленькая/1'
col=nan | val='Средняя (стандарт)/2'
col=nan | val='Большая/3'
col=nan | val='Повышен нажим/4'
col=nan | val='Зачернена/5'
col=nan | val='Отсутствует/6'
col='5. Ладонь, пальцы (Множественный выбор)' | val='Изображены пальцы/1'
col=nan | val='Изображена ладонь/2'
col=nan | val='Положение «варежки»/3'
col=nan | val='Кулак, большой палец снаружи/4'
col=nan | val='Кулак, большой палец не виден/5'
col=nan | val='Отсутствуют/6'
col='5.1. Пальцы (Множественный выбор)' | val='Изображены черточками/1'
col=nan | val='Передана толщина/2'
col=nan | val='Округлые ногти/3'
col=nan | val='Заостренные ногти/4'
col=nan | val='Другое'
col='6. Ноги (одна или обе) (Множественный выбор)' | val='Две ноги в одинаковом положении/1'
col=nan | val='Две ноги в разном положении/2'
col=nan | val='Только одна нога/3'
col=nan | val='Скрыты препятствием/4'
col=nan | val='Отсутствуют/5'
col='6.1 Ноги\xa0 (Множественный выбор)' | val='Сведены вместе/1'
col=nan | val='Слегка расставлены (стандарт)/2'
col=nan | val='Широко расставлены/3'
col=nan | val='Короткие/4'
col=nan | val='Длинные/5'
col=nan | val='Другое'
col='6.2.1. Правая нога (Множественный выбор)' | val='Вертикальна/1'
col=nan | val='Отставлена (стандарт)/2'
col=nan | val='Согнута/3'
col=nan | val='Короткая/4'
col=nan | val='Длинная/5'
col=nan | val='Другое'
col='6.2.2. Левая нога (Множественный выбор)' | val='Вертикальна/1'
col=nan | val='Отставлена (стандарт)/2'
col=nan | val='Согнута/3'
col=nan | val='Короткая/4'
col=nan | val='Длинная/5'
col=nan | val='Другое'
col='6.3. Нога (Множественный выбор)' | val='Вертикальна/1'
col=nan | val='Отставлена (стандарт)/2'
col=nan | val='Согнута/3'
col=nan | val='Короткая/4'
col=nan | val='Длинная/5'
col=nan | val='Другое'
col='7. Ступни (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Маленькие/2'
col=nan | val='Большие/3'
col=nan | val='Повышен нажим/4'
col=nan | val='Зачернены/5'
col=nan | val='Отсутствуют/6'
col=nan | val='Другое'
col='8. Шея (Множественный выбор)' | val='Без особенностей/1'
col=nan | val='Одинарная линия/2'
col=nan | val='Тонкая/3'
col=nan | val='Толстая/4'
col=nan | val='Короткая/5'
col=nan | val='Длинная/6'
col=nan | val='Отсутствует/7'
col='9. Тело (Множественный выбор)' | val='Палочка/1'
col=nan | val='Округлое/2'
col=nan | val='Прямоугольное/3'
col=nan | val='Реалистичное/4'
col=nan | val='Вытянутое/5'
col=nan | val='Широкое/6'
col=nan | val='Отсутствует 7'
col=nan | val='Треугольное'
col=nan | val='Другое'
col='10. Пол (Множественный выбор)' | val='Женский/1'
col=nan | val='Мужской/2'
col=nan | val='Неопределенный/3'
col=nan | val='Признаки пола подчеркнуты/4'
col=nan | val='Подчеркнута генитальная область/5'
col=nan | val='Изображены половые органы/6'
col='11. Одежда (Множественный выбор)' | val='Реалистичное изображение/1'
col=nan | val='Условное изображение/2'
col=nan | val='«Рентгеновский» рисунок/3'
col=nan | val='Отсутствует, тело изображено условно/4'
col=nan | val='Отсутствует, человек обнажен/5'
col='12. Дополнительные детали изображения фигуры (Множественный выбор)' | val='Отсутствуют/1'
col=nan | val='Пуговицы/2'
col=nan | val='Пуп/3'
col=nan | val='Ширинка/4'
col=nan | val='Волосы на теле или конечностях/5'
col=nan | val='Украшения/6'
col=nan | val='Другое'
col=nan | val='Ремень/пояс'
col='12.2. Пуговицы (Одиночный выбор)' | val=nan
col='12.6. Украшения, узор на одежде (Одиночный выбор)' | val=nan
col='13. Дополнительно (в руке или рядом) (Множественный выбор)' | val='Игрушка, шарик/1'
col=nan | val='Цветок/2'
col=nan | val='Животное/3'
col=nan | val='Палка/4'
col=nan | val='Меч, нож, топор/5'
col=nan | val='Пистолет, ружье/6'
col=nan | val='Шприц'
col=nan | val='Сигарета'
col=nan | val='Сумка'
col=nan | val='Телефон'
col=nan | val='Зонт'
col=nan | val='Дополнительные предметы отсутствуют'
col='14. Фон (Множественный выбор)' | val='Отсутствует/1'
col=nan | val='Штриховка/2'
col=nan | val='Опорная линия/3'
col=nan | val='Заштрихованное облако/4'
col=nan | val='Пейзаж/5'
col=nan | val='Пейзаж преобладает над изображением человека/6'
col=nan | val='Дождь'
col=nan | val='Солнце'
col=nan | val='Земля'
col=nan | val='Другое'
col='14.1 Площадь штриховки (Одиночный выбор)' | val=nan
col='14.2 Нажим (Одиночный выбор)' | val=nan
col='Шея отделена от тела линией (Одиночный выбор)' | val=nan

In [ ]:
cols = pd.Series(df.columns, dtype="object")
vals = df.iloc[0]

filled = cols.ffill()

new_columns = []
for c, v, base in zip(cols, vals, filled):
    if pd.isna(v):
        new_columns.append("" if pd.isna(base) else str(base))
    else:
        new_columns.append(f"{base} ({v})")

df.columns = new_columns
df = df.iloc[1:].reset_index(drop=True)
df

,Укажите код-идентификатор обследуемого (Свободный ответ),Укажите возраст обследуемого (Свободный ответ),Укажите пол обследуемого (Одиночный выбор),1 Расположение на листе (Множественный выбор) (Без особенностей/1),1 Расположение на листе (Множественный выбор) (Смещение вправо/2),1 Расположение на листе (Множественный выбор) (Смещение влево/3),1 Расположение на листе (Множественный выбор) (Смещение вверх/4),1 Расположение на листе (Множественный выбор) (Смещение вниз/5),1 Расположение на листе (Множественный выбор) (Размещение в углу/6),"1 Расположение на листе (Множественный выбор) (Изображение обрезано - есть место для дорисовки, но не дорисовано)",...,14. Фон (Множественный выбор) (Заштрихованное облако/4),14. Фон (Множественный выбор) (Пейзаж/5),14. Фон (Множественный выбор) (Пейзаж преобладает над изображением человека/6),14. Фон (Множественный выбор) (Дождь),14. Фон (Множественный выбор) (Солнце),14. Фон (Множественный выбор) (Земля),14. Фон (Множественный выбор) (Другое),14.1 Площадь штриховки (Одиночный выбор),14.2 Нажим (Одиночный выбор),Шея отделена от тела линией (Одиночный выбор)
0,Код,Возраст,Пол,1,2,3,4,5,6,7,...,249,250,251,252,1058,1059,1060,1062,1063,253
1,ЧУВ6лм1кл_6,6,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
2,ЧУВ6лм1кл_5,6,мужской,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
3,ЧУВ6лм1кл_4,6,мужской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
4,ЧУВ5лмдс_51,5,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8578,ЧУВ5лждс (76),5,женский,Без особенностей/1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8579,ЧУВ5лждс (75),5,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
8580,ЧУВ6лмдс,6,мужской,NaN,NaN,NaN,Смещение вверх/4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8581,1,1,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,Пейзаж/5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Галстук
8582,1,1,женский,NaN,NaN,NaN,NaN,NaN,Размещение в углу/6,NaN,...,NaN,NaN,NaN,NaN,Солнце,NaN,NaN,NaN,NaN,Бусы

In [ ]:
# Очистка от неразрывных пробелов ('\xa0')

def count_xao_in_df(df):
    n = 0
    for c in df.columns:
        if isinstance(c, str):
            n += c.count("\xa0")
    for col in df.columns:
        s = df[col]
        for v in s:
            if isinstance(v, str):
                n += v.count("\xa0")
    return n

def strip_xao(x):
    if isinstance(x, str):
        return x.replace("\xa0", " ")
    return x

In [ ]:
print(f"Кол-во'\\xa0' до очистки {count_xao_in_df(df)}")

df.columns = [strip_xao(c) if isinstance(c, str) else c for c in df.columns]
df = df.map(strip_xao)

print("Кол-во '\\xa0' после очистки:", count_xao_in_df(df))

Кол-во'\xa0' до очистки 39
Кол-во '\xa0' после очистки: 0

In [ ]:
df

,Укажите код-идентификатор обследуемого (Свободный ответ),Укажите возраст обследуемого (Свободный ответ),Укажите пол обследуемого (Одиночный выбор),1 Расположение на листе (Множественный выбор) (Без особенностей/1),1 Расположение на листе (Множественный выбор) (Смещение вправо/2),1 Расположение на листе (Множественный выбор) (Смещение влево/3),1 Расположение на листе (Множественный выбор) (Смещение вверх/4),1 Расположение на листе (Множественный выбор) (Смещение вниз/5),1 Расположение на листе (Множественный выбор) (Размещение в углу/6),"1 Расположение на листе (Множественный выбор) (Изображение обрезано - есть место для дорисовки, но не дорисовано)",...,14. Фон (Множественный выбор) (Заштрихованное облако/4),14. Фон (Множественный выбор) (Пейзаж/5),14. Фон (Множественный выбор) (Пейзаж преобладает над изображением человека/6),14. Фон (Множественный выбор) (Дождь),14. Фон (Множественный выбор) (Солнце),14. Фон (Множественный выбор) (Земля),14. Фон (Множественный выбор) (Другое),14.1 Площадь штриховки (Одиночный выбор),14.2 Нажим (Одиночный выбор),Шея отделена от тела линией (Одиночный выбор)
0,Код,Возраст,Пол,1,2,3,4,5,6,7,...,249,250,251,252,1058,1059,1060,1062,1063,253
1,ЧУВ6лм1кл_6,6,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
2,ЧУВ6лм1кл_5,6,мужской,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
3,ЧУВ6лм1кл_4,6,мужской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
4,ЧУВ5лмдс_51,5,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8578,ЧУВ5лждс (76),5,женский,Без особенностей/1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8579,ЧУВ5лждс (75),5,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
8580,ЧУВ6лмдс,6,мужской,NaN,NaN,NaN,Смещение вверх/4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8581,1,1,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,Пейзаж/5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Галстук
8582,1,1,женский,NaN,NaN,NaN,NaN,NaN,Размещение в углу/6,NaN,...,NaN,NaN,NaN,NaN,Солнце,NaN,NaN,NaN,NaN,Бусы

In [ ]:
# Создаём словарь для первой строки, чтобы обработать названия признаков

features_to_rename = dict()

for col, val in df.iloc[0].items():
    features_to_rename[col] = col

In [ ]:
def process_feature_name(val):
    if not isinstance(val, str):
        return val

    s = val

    # 1. Удаляем только неразрывные пробелы и заменяем их обычными пробелами
    s = s.replace('\xa0', ' ')

    # 2. Удаляем стандартные пометки о типе выбора
    s = s.replace('(Одиночный выбор)', '')
    s = s.replace('(Множественный выбор)', '')

    # 3. Чистим только внутренности скобок
    def parentheses_clean(subs):
        s2 = subs

        if re.search(r'/\s*\d', s2):
            s2 = re.split(r'/\s*\d', s2, maxsplit=1)[0]

        s2 = s2.replace('=>', ' ')
        s2 = re.sub(r'\d+(?:\.\d+)*', '', s2)
        s2 = re.sub(r'\s+', ' ', s2)
        return s2.strip()

    stack = []
    spans = []
    for i, ch in enumerate(s):
        if ch == '(':
            stack.append(i)
        elif ch == ')' and stack:
            start = stack.pop()
            spans.append((start, i))

    for start, end in sorted(spans, key=lambda t: t[0], reverse=True):
        txt = s[start + 1:end]

        if "=>" in txt or re.search(r'[0-9]', txt) or re.search(r'/\s*\d', txt):
            new_txt = parentheses_clean(txt)
        else:
            new_txt = re.sub(r'\s+', ' ', txt).strip()

        new_txt = new_txt.lower()
        s = s[:start + 1] + new_txt + s[end:]

    # 4. Удаляем ведущие (начальные) числа, точки и лишние разделители только в НАЧАЛЕ строки
    s = re.sub(r'^\s*(?:\d+\.)*\d*\s*', '', s)

    # 5. Удаляем лишние пробелы ПО ВСЕЙ СТРОКЕ (заменяем все последовательности пробелов на один пробел)
    s = re.sub(r' +', ' ', s)

    # 6. Нормализуем слеши: ровно один пробел до и после '/'
    s = re.sub(r'\s*/\s*', ' / ', s)
    s = re.sub(r' +', ' ', s)

    # 7. Заменяем двойные кавычки одинарными
    s = s.replace('"', "'")
    s = s.replace('«', "'")
    s = s.replace('»', "'")

    # 8. Удаляем пробелы по краям
    s = s.strip()
    return s

processed_features = {}
for k, v in features_to_rename.items():
    processed_features[k] = process_feature_name(v)

# with open("features_to_rename_processed_1.json", "w", encoding="utf-8") as f:
#     json.dump(processed_features, f, ensure_ascii=False, indent=2)

In [ ]:
# Дололнительно обрабатываем отдельные признаки

manually_renaming_features = {
    "Укажите код-идентификатор обследуемого (Свободный ответ)": "Код-идентификатор обследуемого",
    "Укажите возраст обследуемого (Свободный ответ)": "Возраст обследуемого",
    "Укажите пол обследуемого (Одиночный выбор)": "Пол обследуемого",
}

In [ ]:
for old_feat, new_feat in manually_renaming_features.items():
    processed_features[old_feat] = new_feat

# with open("features_to_rename_processed_2.json", "w", encoding="utf-8") as f:
#     json.dump(processed_features, f, ensure_ascii=False, indent=2)

In [ ]:
mismatched_keys = [c for c in df.columns if c not in processed_features]
print(f"Кол-во несовпадающих признаков: {len(mismatched_keys)}")

Кол-во несовпадающих признаков: 0

In [ ]:
# Таблица с необработанными признаками

df

,Укажите код-идентификатор обследуемого (Свободный ответ),Укажите возраст обследуемого (Свободный ответ),Укажите пол обследуемого (Одиночный выбор),1 Расположение на листе (Множественный выбор) (Без особенностей/1),1 Расположение на листе (Множественный выбор) (Смещение вправо/2),1 Расположение на листе (Множественный выбор) (Смещение влево/3),1 Расположение на листе (Множественный выбор) (Смещение вверх/4),1 Расположение на листе (Множественный выбор) (Смещение вниз/5),1 Расположение на листе (Множественный выбор) (Размещение в углу/6),"1 Расположение на листе (Множественный выбор) (Изображение обрезано - есть место для дорисовки, но не дорисовано)",...,14. Фон (Множественный выбор) (Заштрихованное облако/4),14. Фон (Множественный выбор) (Пейзаж/5),14. Фон (Множественный выбор) (Пейзаж преобладает над изображением человека/6),14. Фон (Множественный выбор) (Дождь),14. Фон (Множественный выбор) (Солнце),14. Фон (Множественный выбор) (Земля),14. Фон (Множественный выбор) (Другое),14.1 Площадь штриховки (Одиночный выбор),14.2 Нажим (Одиночный выбор),Шея отделена от тела линией (Одиночный выбор)
0,Код,Возраст,Пол,1,2,3,4,5,6,7,...,249,250,251,252,1058,1059,1060,1062,1063,253
1,ЧУВ6лм1кл_6,6,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
2,ЧУВ6лм1кл_5,6,мужской,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
3,ЧУВ6лм1кл_4,6,мужской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
4,ЧУВ5лмдс_51,5,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8578,ЧУВ5лждс (76),5,женский,Без особенностей/1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8579,ЧУВ5лждс (75),5,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
8580,ЧУВ6лмдс,6,мужской,NaN,NaN,NaN,Смещение вверх/4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8581,1,1,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,Пейзаж/5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Галстук
8582,1,1,женский,NaN,NaN,NaN,NaN,NaN,Размещение в углу/6,NaN,...,NaN,NaN,NaN,NaN,Солнце,NaN,NaN,NaN,NaN,Бусы

In [ ]:
# Таблица с обработанными признаками

df = df.rename(columns=processed_features)
df

,Код-идентификатор обследуемого,Возраст обследуемого,Пол обследуемого,Расположение на листе (без особенностей),Расположение на листе (смещение вправо),Расположение на листе (смещение влево),Расположение на листе (смещение вверх),Расположение на листе (смещение вниз),Расположение на листе (размещение в углу),"Расположение на листе (изображение обрезано - есть место для дорисовки, но не дорисовано)",...,Фон (заштрихованное облако),Фон (пейзаж),Фон (пейзаж преобладает над изображением человека),Фон (дождь),Фон (солнце),Фон (земля),Фон (другое),Площадь штриховки,Нажим,Шея отделена от тела линией
0,Код,Возраст,Пол,1,2,3,4,5,6,7,...,249,250,251,252,1058,1059,1060,1062,1063,253
1,ЧУВ6лм1кл_6,6,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
2,ЧУВ6лм1кл_5,6,мужской,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
3,ЧУВ6лм1кл_4,6,мужской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
4,ЧУВ5лмдс_51,5,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Шея отсутствует
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8578,ЧУВ5лждс (76),5,женский,Без особенностей/1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8579,ЧУВ5лждс (75),5,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
8580,ЧУВ6лмдс,6,мужской,NaN,NaN,NaN,Смещение вверх/4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Просто линия
8581,1,1,женский,NaN,NaN,NaN,NaN,Смещение вниз/5,NaN,NaN,...,NaN,Пейзаж/5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Галстук
8582,1,1,женский,NaN,NaN,NaN,NaN,NaN,Размещение в углу/6,NaN,...,NaN,NaN,NaN,NaN,Солнце,NaN,NaN,NaN,NaN,Бусы

In [ ]:
# Вторая строка содержит номера признаков. Присвоим номера признакам 'Возраст' и 'Пол'

df.iat[0, 0] = 10000
df.iat[0, 1] = 2001
df.iat[0, 2] = 2002

In [ ]:
# Проверим типы данных в нулевой строке

row0 = df.iloc[0]
types = row0.map(lambda x: "EMPTY" if pd.isna(x) else type(x))
print(types.value_counts())

0
<class 'int'>              305
<class 'numpy.float64'>      6
Name: count, dtype: int64

In [ ]:
# import pandas as pd
# import numpy as np

# for j in range(df.shape[1]):
#     v = df.iat[0, j]

#     if pd.isna(v):
#         continue

#     col = df.columns[j]

#     if isinstance(v, (np.floating, float)):
#         xf = float(v)
#         if xf.is_integer():
#             if np.issubdtype(df.dtypes.iloc[j], np.floating):
#                 df[col] = df[col].astype("object")
#             df.iat[0, j] = int(xf)
#         continue

#     if isinstance(v, np.integer):
#         if np.issubdtype(df.dtypes.iloc[j], np.floating):
#             df[col] = df[col].astype("object")
#         df.iat[0, j] = int(v)

# row0 = df.iloc[0]

# from collections import defaultdict

# type_tag = row0.map(lambda x: "MISSING" if pd.isna(x) else type(x))
# print(f"Уникальных типов: {type_tag.nunique()}")

# by_type = defaultdict(list)
# for col, v in row0.items():
#     by_type["MISSING" if pd.isna(v) else type(v)].append((col, v))

# for t, items in by_type.items():
#     print(f"\n{t} cnt: {len(items)} == {df.shape[1]}")
#     for col, v in items[:3]:
#         print(f" - {col} => {v!r}")

In [ ]:
# Проверим уникальные типы данных по всей таблице

by_type = defaultdict(list)

for j in range(df.shape[1]):
    col_name = df.columns[j]
    for i in range(df.shape[0]):
        v = df.iat[i, j]
        t = "EMPTY" if pd.isna(v) else type(v)
        by_type[t].append((i, j, col_name, v))

print("Уникальные типы:", len(by_type))
for t, items in sorted(by_type.items(), key=lambda kv: len(kv[1]), reverse=True):
    print(f"\n{t} (cnt = {len(items)})")
    for i, j, col_name, v in items[:3]:
        print(f" - (row={i}, col_idx={j}, col={col_name!r}) => {v!r}")

KeyboardInterrupt:

In [ ]:
row0 = df.iloc[0]
ok = row0.nunique(dropna=False) == df.shape[1]
print(f"Число уникальных значений в 0-й строке равно числу столбцов: {ok}")

Число уникальных значений в 0-й строке равно числу столбцов: True

In [ ]:
df

,Код-идентификатор обследуемого,Возраст обследуемого,Пол обследуемого,Расположение на листе (без особенностей),Расположение на листе (смещение вправо),Расположение на листе (смещение влево),Расположение на листе (смещение вверх),Расположение на листе (смещение вниз),Расположение на листе (размещение в углу),Расположение на листе (изображение обрезано),...,Дополнительно (в руке или рядом) (сумка),Дополнительно (в руке или рядом) (вариант 'ничего из перечисленного'),Фон (отсутствует),Фон (штриховка),Фон (опорная линия),Фон (заштрихованное облако),Фон (пейзаж),Фон (пейзаж преобладает над изображением человека),Фон (дождь),Шея отделена от тела линией
0,10000,2001,2002,1,2,3,4,5,6,7,...,244,245,246,247,248,249,250,251,252,253
1,2172ДД9лм3кл,9,мужской,NaN,NaN,Смещение влево/3,NaN,Смещение вниз/5,NaN,NaN,...,NaN,ничего из перечисленного,Отсутствует/1,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
2,2171ЯИ10лм3кл,10,мужской,NaN,Смещение вправо/2,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,ничего из перечисленного,Отсутствует/1,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
3,2170МЕ9лж3кл,9,женский,Без особенностей/1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,ничего из перечисленного,Отсутствует/1,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
4,2169ГМ9лм3кл,9,мужской,Без особенностей/1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,ничего из перечисленного,Отсутствует/1,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4405,7,9,мужской,NaN,Смещение вправо/2,NaN,NaN,NaN,NaN,NaN,...,NaN,ничего из перечисленного,NaN,NaN,NaN,NaN,Пейзаж/5,NaN,NaN,NaN
4406,1,7,мужской,NaN,NaN,Смещение влево/3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Пейзаж/5,Пейзаж преобладает над изображением человека/6,NaN,NaN
4407,123,5,женский,NaN,NaN,Смещение влево/3,NaN,Смещение вниз/5,NaN,NaN,...,NaN,NaN,Отсутствует/1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4408,АА12,12,мужской,NaN,NaN,NaN,NaN,NaN,Размещение в углу/6,NaN,...,NaN,NaN,NaN,Штриховка/2,NaN,NaN,NaN,NaN,NaN,NaN
4409,ФФ12,10,мужской,NaN,NaN,NaN,NaN,NaN,Размещение в углу/6,NaN,...,NaN,ничего из перечисленного,NaN,Штриховка/2,NaN,NaN,Пейзаж/5,NaN,NaN,NaN

In [ ]:
features = df.iloc[0]
print(f"Все признаки имеют уникальные названия: {features.nunique(dropna=False)} == {features.shape[0]}")

Все признаки имеют уникальные названия: 256 == 256

In [ ]:
df.to_excel("1_1_features_and_labels.xlsx", index=False)

KeyboardInterrupt: