In [135]:
import math
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment

In [136]:
input_file = "./2_2_preprocessing of feature labels.xlsx"
df = pd.read_excel(input_file)
df = df.iloc[1:].reset_index(drop=True)  # отбрасываем номера признаков
df.shape

(8452, 311)

In [137]:
df

,Код-идентификатор обследуемого,Возраст обследуемого,Пол обследуемого,Расположение на листе (без особенностей),Расположение на листе (смещение вправо),Расположение на листе (смещение влево),Расположение на листе (смещение вверх),Расположение на листе (смещение вниз),Расположение на листе (размещение в углу),"Расположение на листе (изображение обрезано - есть место для дорисовки, но не дорисовано)",...,Фон (заштрихованное облако),Фон (пейзаж),Фон (пейзаж преобладает над изображением человека),Фон (дождь),Фон (солнце),Фон (земля),Фон (другое),Площадь штриховки,Нажим,Шея отделена от тела линией
0,ЧУВ6лм1кл_6,6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
1,ЧУВ6лм1кл_5,6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
2,ЧУВ6лм1кл_4,6,мужской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
3,ЧУВ5лмдс_51,5,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
4,ЧУВ5лмдс_50,5,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8447,ЧУВ5лждс (79),5,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,пейзаж,NaN,NaN,солнце,земля,NaN,NaN,NaN,ничего из перечисленного
8448,ЧУВ5лждс (78),5,женский,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,просто линия
8449,ЧУВ5лждс (77),5,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
8450,ЧУВ5лждс (76),5,женский,без особенностей,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,просто линия
8451,ЧУВ5лждс (75),5,женский,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного

In [138]:
ages_to_exclude = [
    16,
    63,
    72,
]

ages_intervals = {
    4: "4-6",
    5: "4-6",
    6: "4-6",
    7: "7-9",
    8: "7-9",
    9: "7-9",
    10: "10-12",
    11: "10-12",
    12: "10-12",
    13: "13-15",
    14: "13-15",
    15: "13-15",
}

age_col = "Возраст обследуемого"

ages_numeric = pd.to_numeric(df[age_col], errors="coerce")
n_rows_excluded_by_age = int(ages_numeric.isin(ages_to_exclude).sum())

df = df.loc[~ages_numeric.isin(ages_to_exclude)].reset_index(drop=True)

ages_numeric = pd.to_numeric(df[age_col], errors="coerce")
df[age_col] = ages_numeric.map(ages_intervals)

print(f"Строк исключено: {n_rows_excluded_by_age} ({n_rows_excluded_by_age} == {4})")

Строк исключено: 4 (4 == 4)

In [139]:
df

,Код-идентификатор обследуемого,Возраст обследуемого,Пол обследуемого,Расположение на листе (без особенностей),Расположение на листе (смещение вправо),Расположение на листе (смещение влево),Расположение на листе (смещение вверх),Расположение на листе (смещение вниз),Расположение на листе (размещение в углу),"Расположение на листе (изображение обрезано - есть место для дорисовки, но не дорисовано)",...,Фон (заштрихованное облако),Фон (пейзаж),Фон (пейзаж преобладает над изображением человека),Фон (дождь),Фон (солнце),Фон (земля),Фон (другое),Площадь штриховки,Нажим,Шея отделена от тела линией
0,ЧУВ6лм1кл_6,4-6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
1,ЧУВ6лм1кл_5,4-6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
2,ЧУВ6лм1кл_4,4-6,мужской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
3,ЧУВ5лмдс_51,4-6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
4,ЧУВ5лмдс_50,4-6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,шея отсутствует
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8443,ЧУВ5лждс (79),4-6,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,пейзаж,NaN,NaN,солнце,земля,NaN,NaN,NaN,ничего из перечисленного
8444,ЧУВ5лждс (78),4-6,женский,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,просто линия
8445,ЧУВ5лждс (77),4-6,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного
8446,ЧУВ5лждс (76),4-6,женский,без особенностей,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,просто линия
8447,ЧУВ5лждс (75),4-6,женский,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ничего из перечисленного

In [140]:
list(df.columns[1:])

['Возраст обследуемого',
 'Пол обследуемого',
 'Расположение на листе (без особенностей)',
 'Расположение на листе (смещение вправо)',
 'Расположение на листе (смещение влево)',
 'Расположение на листе (смещение вверх)',
 'Расположение на листе (смещение вниз)',
 'Расположение на листе (размещение в углу)',
 'Расположение на листе (изображение обрезано - есть место для дорисовки, но не дорисовано)',
 'Расположение на листе (изоброжение обрезано - обрезан краем листа / нет места для дорисовки)',
 'Степень смещения вправо',
 'Степень смещения влево',
 'Степень смещения вверх',
 'Степень смещения вниз',
 'Размещение в углу',
 'Что обрезано (голова)',
 'Что обрезано (одна рука)',
 'Что обрезано (обе руки)',
 'Что обрезано (ноги)',
 'Размер рисунка',
 'Ракурс',
 'Поза',
 'Фигура в движении',
 'Способ изображения',
 'Изображение персонажа',
 'Персонаж',
 'Нажим (без особенностей)',
 'Нажим (слабый)',
 'Нажим (сильный)',
 'Нажим (сильно варьирует)',
 'Особенности линии (без особенностей)',
 'Особенности линии (множественные)',
 'Особенности линии (эскизные)',
 "Особенности линии ('кусочные')",
 'Особенности линии (недоведенные)',
 "Особенности линии ('промахивающиеся')",
 'Особенности линии (другое)',
 'Множественные, степень выраженности',
 'Эскизные, степень выраженности',
 "'Кусочные', степень выраженности",
 'Недоведенные, степень выраженности',
 "'Промахивающиеся', степень выраженности",
 'Аккуратность рисунка',
 'Штриховка',
 'Нажим штриховки (без особенностей)',
 'Нажим штриховки (слабый)',
 'Нажим штриховки (сильный)',
 'Нажим штриховки (варьирует)',
 'Аккуратность штриховки (очень низкая)',
 'Аккуратность штриховки (низкая)',
 'Аккуратность штриховки (средняя (стандарт))',
 'Аккуратность штриховки (высокая)',
 'Аккуратность штриховки (очень высокая)',
 'Аккуратность штриховки (разные виды штриховок)',
 'Детализированность',
 'Стирания, исправления',
 'Устойчивость изображенного человека',
 'Грубые нарушения рисунка (отсутствуют)',
 'Грубые нарушения рисунка (отклонение от вертикали)',
 'Грубые нарушения рисунка (нарушение пропорций)',
 'Грубые нарушения рисунка (грубая асимметрия)',
 'Изображение в рамке',
 'Голова (без особенностей)',
 'Голова (маленькая)',
 'Голова (большая)',
 'Голова (искажена форма)',
 'Голова (зачерненная / заштрихованная)',
 'Голова (отсутствует)',
 'Детали (лицо) (глаза (один или оба))',
 'Детали (лицо) (нос)',
 'Детали (лицо) (рот)',
 'Детали (лицо) (уши)',
 'Детали (лицо) (лоб)',
 'Детали (лицо) (волосы (шапка))',
 'Детали (лицо) (другое)',
 'Детали (лицо) (отсутствуют все указанные выше пункты)',
 'Два глаза одинаковые',
 'Форма глаз (точка)',
 'Форма глаз (черточка)',
 'Форма глаз (круг)',
 'Форма глаз (овал, реалистичная форма)',
 "Форма глаз ('мультяшные')",
 'Форма глаз (форма искажена)',
 'Форма глаз (отсутствуют)',
 'Форма левого глаза (точка)',
 'Форма левого глаза (черточка)',
 'Форма левого глаза (круг)',
 'Форма левого глаза (овал, реалистичная форма)',
 "Форма левого глаза ('мультяшные')",
 'Форма левого глаза (форма искажена)',
 'Форма левого глаза (отсутствует)',
 'Форма правого глаза (точка)',
 'Форма правого глаза (черточка)',
 'Форма правого глаза (круг)',
 'Форма правого глаза (овал, реалистичная форма)',
 "Форма правого глаза ('мультяшные')",
 'Форма правого глаза (форма искажена)',
 'Форма правого глаза (отсутствует)',
 'Размер глаз',
 'Размер левого глаза',
 'Размер правого глаза',
 'Дополнительные особенности глаз (без особенностей)',
 'Дополнительные особенности глаз (подчеркнутый контур)',
 "Дополнительные особенности глаз ('пустые')",
 'Дополнительные особенности глаз (зачернена радужка или весь глаз)',
 'Дополнительные особенности глаз (один или оба глаза закрыты волосами или шапкой)',
 'Дополнительные особенности глаз (изображены очки (прозрачные))',
 'Дополнительные особенности глаз (изображены темные очки)',
 'Дополнительные особенности глаз (закрыты)',
 'Дополнительные особенности глаз (полузакрыты (прищур))',
 'Дополнительные особенности правого глаза (без особенностей)',
 'Дополнительные особенности правого глаза (подчеркнутый контур)',
 "Дополнительные особенности правого глаза ('пустые')",
 'Дополнительные особенности правого глаза (зачернена радужка или весь глаз)',
 'Дополнительные особенности правого глаза (закрыт волосами или шапкой)',
 'Дополнительные особенности правого глаза (изображены очки (прозрачные))',
 'Дополнительные особенности правого глаза (изображены темные очки)',
 'Дополнительные особенности правого глаза (закрыт)',
 'Дополнительные особенности правого глаза (полузакрыт (прищур))',
 'Дополнительные особенности левого глаза (без особенностей)',
 'Дополнительные особенности левого глаза (подчеркнутый контур)',
 "Дополнительные особенности левого глаза ('пустые')",
 'Дополнительные особенности левого глаза (зачернена радужка или весь глаз)',
 'Дополнительные особенности левого глаза (закрыт волосами или шапкой)',
 'Дополнительные особенности левого глаза (изображены очки (прозрачные))',
 'Дополнительные особенности левого глаза (изображены темные очки)',
 'Дополнительные особенности левого глаза (закрыт)',
 'Дополнительные особенности левого глаза (полузакрыт (прищур))',
 'Ресницы',
 'Нос (без особенностей)',
 'Нос (увеличен размер)',
 'Нос (усилен нажим)',
 'Нос (другое)',
 'Нос (отсутствует)',
 'Рот',
 'Форма рта',
 'Положение рта / губ',
 'Зубы',
 'Язык',
 'Уши (без особенностей)',
 'Уши (усилен нажим)',
 'Уши (преувеличен размер)',
 'Уши (другое)',
 'Уши (отсутствуют)',
 'Лоб (маленький)',
 'Лоб (средний (стандарт))',
 'Лоб (большой)',
 'Лоб (скрыт волосами или шапкой)',
 'Лоб (скрыт волосами, усилен нажим)',
 'Лоб (другое)',
 'Лоб (отсутствует)',
 'Волосы или шапка (без особенностей)',
 'Волосы или шапка (нарисованы небрежно)',
 'Волосы или шапка (нарисованы особо старательно)',
 'Волосы или шапка (другое)',
 'Волосы или шапка (отсутствуют)',
 'Дополнительные детали на лице (брови)',
 'Дополнительные детали на лице (усы и / или борода)',
 'Дополнительные детали на лице (морщины)',
 'Дополнительные детали на лице (маска)',
 'Дополнительные детали на лице (рисунки на лице)',
 'Дополнительные детали на лице (другое)',
 'Дополнительные детали на лице (отсутствуют)',
 'Руки (одна или обе)',
 'Положение рук (слегка отставлены (стандарт))',
 'Положение рук (прижаты к телу (от верха до локтя))',
 'Положение рук (свободно опущены)',
 'Положение рук (сильно отставлены)',
 'Положение рук (вытянуты в стороны или вперед)',
 'Положение рук (подняты)',
 'Положение рук (дополнительно)',
 'Положение рук (за спиной или в карманах)',
 'Положение рук (на фоне тела)',
 'Положение рук (скрещены на груди)',
 'Положение рук (уперты в бока)',
 'Положение рук (закрывают генитальную область)',
 'Положение рук (прижаты к голове)',
 'Положение рук (другое)',
 'Положение правой руки',
 'Положение правой руки.1',
 'Положение левой руки',
 'Положение левой руки.1',
 'Положение руки (слегка отставлена (стандарт))',
 'Положение руки (прижата к телу (от верха до локтя))',
 'Положение руки (свободно опущена)',
 'Положение руки (сильно отставлена)',
 'Положение руки (вытянута в сторону или вперед)',
 'Положение руки (поднята)',
 'Положение руки (дополнительно)',
 'Положение руки (за спиной или в кармане)',
 'Положение руки (на фоне тела)',
 'Положение руки (уперта в бок)',
 'Положение руки (закрывает генитальную область)',
 'Положение руки (прижата к голове)',
 'Положение руки (другое)',
 'Кисть (маленькая)',
 'Кисть (средняя (стандарт))',
 'Кисть (большая)',
 'Кисть (повышен нажим)',
 'Кисть (зачернена)',
 'Кисть (отсутствует)',
 'Ладонь, пальцы (изображены пальцы)',
 'Ладонь, пальцы (изображена ладонь)',
 "Ладонь, пальцы (положение 'варежки')",
 'Ладонь, пальцы (кулак, большой палец снаружи)',
 'Ладонь, пальцы (кулак, большой палец не виден)',
 'Ладонь, пальцы (отсутствуют)',
 'Пальцы (изображены черточками)',
 'Пальцы (передана толщина)',
 'Пальцы (округлые ногти)',
 'Пальцы (заостренные ногти)',
 'Пальцы (другое)',
 'Ноги (одна или обе) (две ноги в одинаковом положении)',
 'Ноги (одна или обе) (две ноги в разном положении)',
 'Ноги (одна или обе) (только одна нога)',
 'Ноги (одна или обе) (скрыты препятствием)',
 'Ноги (одна или обе) (отсутствуют)',
 'Ноги (сведены вместе)',
 'Ноги (слегка расставлены (стандарт))',
 'Ноги (широко расставлены)',
 'Ноги (короткие)',
 'Ноги (длинные)',
 'Ноги (другое)',
 'Правая нога (вертикальна)',
 'Правая нога (отставлена (стандарт))',
 'Правая нога (согнута)',
 'Правая нога (короткая)',
 'Правая нога (длинная)',
 'Правая нога (другое)',
 'Левая нога (вертикальна)',
 'Левая нога (отставлена (стандарт))',
 'Левая нога (согнута)',
 'Левая нога (короткая)',
 'Левая нога (длинная)',
 'Левая нога (другое)',
 'Нога (вертикальна)',
 'Нога (отставлена (стандарт))',
 'Нога (согнута)',
 'Нога (короткая)',
 'Нога (длинная)',
 'Нога (другое)',
 'Ступни (без особенностей)',
 'Ступни (маленькие)',
 'Ступни (большие)',
 'Ступни (повышен нажим)',
 'Ступни (зачернены)',
 'Ступни (отсутствуют)',
 'Ступни (другое)',
 'Шея (без особенностей)',
 'Шея (одинарная линия)',
 'Шея (тонкая)',
 'Шея (толстая)',
 'Шея (короткая)',
 'Шея (длинная)',
 'Шея (отсутствует)',
 'Тело (палочка)',
 'Тело (округлое)',
 'Тело (прямоугольное)',
 'Тело (реалистичное)',
 'Тело (вытянутое)',
 'Тело (широкое)',
 'Тело (отсутствует)',
 'Тело (треугольное)',
 'Тело (другое)',
 'Пол (женский)',
 'Пол (мужской)',
 'Пол (неопределенный)',
 'Пол (признаки пола подчеркнуты)',
 'Пол (подчеркнута генитальная область)',
 'Пол (изображены половые органы)',
 'Одежда (реалистичное изображение)',
 'Одежда (условное изображение)',
 "Одежда ('рентгеновский' рисунок)",
 'Одежда (отсутствует, тело изображено условно)',
 'Одежда (отсутствует, человек обнажен)',
 'Дополнительные детали изображения фигуры (отсутствуют)',
 'Дополнительные детали изображения фигуры (пуговицы)',
 'Дополнительные детали изображения фигуры (пуп)',
 'Дополнительные детали изображения фигуры (ширинка)',
 'Дополнительные детали изображения фигуры (волосы на теле или конечностях)',
 'Дополнительные детали изображения фигуры (украшения)',
 'Дополнительные детали изображения фигуры (другое)',
 'Дополнительные детали изображения фигуры (ремень / пояс)',
 'Пуговицы',
 'Украшения, узор на одежде',
 'Дополнительно (в руке или рядом) (игрушка, шарик)',
 'Дополнительно (в руке или рядом) (цветок)',
 'Дополнительно (в руке или рядом) (животное)',
 'Дополнительно (в руке или рядом) (палка)',
 'Дополнительно (в руке или рядом) (меч, нож, топор)',
 'Дополнительно (в руке или рядом) (пистолет, ружье)',
 'Дополнительно (в руке или рядом) (шприц)',
 'Дополнительно (в руке или рядом) (сигарета)',
 'Дополнительно (в руке или рядом) (сумка)',
 'Дополнительно (в руке или рядом) (телефон)',
 'Дополнительно (в руке или рядом) (зонт)',
 'Дополнительно (в руке или рядом) (дополнительные предметы отсутствуют)',
 'Фон (отсутствует)',
 'Фон (штриховка)',
 'Фон (опорная линия)',
 'Фон (заштрихованное облако)',
 'Фон (пейзаж)',
 'Фон (пейзаж преобладает над изображением человека)',
 'Фон (дождь)',
 'Фон (солнце)',
 'Фон (земля)',
 'Фон (другое)',
 'Площадь штриховки',
 'Нажим',
 'Шея отделена от тела линией']

In [141]:
# Исключаем неразмеченные признаки (7 признаков)
# (№i - номера страниц в директории './3_analysis/3_reports')
unlabled_features = [
    "Дополнительные особенности правого глаза (изображены темные очки)",  # 9
    "Положение руки (закрывает генитальную область)",  # 13
    "Положение руки (прижата к голове)",  # 13
    "Нога (отставлена (стандарт))",  # 15
    "Нога (согнута)",  # 15
    "Нога (короткая)",  # 15
    "Нога (длинная)",  # 15
]

old_shape = df.shape

df = df.drop(columns=unlabled_features)
new_shape = df.shape

print(f"Проверка: {old_shape[0], old_shape[1] - len(unlabled_features)} == {new_shape}")

Проверка: (8448, 304) == (8448, 304)

In [142]:
features_to_merge = {
    "Голова (размер)": {
        "Голова (маленькая)": "маленькая",
        "Голова (большая)": "большая",  
    },
    "Глаза (форма)": {
        "Форма глаз (точка)": "точка",
        "Форма глаз (черточка)": "черточка",
        "Форма глаз (круг)": "круг",
        "Форма глаз (овал, реалистичная форма)": "овал, реалистичная форма",
    },
    "Левый глаз (форма)": {
        "Форма левого глаза (точка)": "точка",
        "Форма левого глаза (черточка)": "черточка",
        "Форма левого глаза (круг)": "круг",
        "Форма левого глаза (овал, реалистичная форма)": "овал, реалистичная форма",
    },
    "Правый глаз (форма)": {
        "Форма правого глаза (точка)": "точка",
        "Форма правого глаза (черточка)": "черточка",
        "Форма правого глаза (круг)": "круг",
        "Форма правого глаза (овал, реалистичная форма)": "овал, реалистичная форма",
    },
    "Лоб (размер)": {
        "Лоб (маленький)": "маленький",
        "Лоб (средний (стандарт))": "средний (стандарт)",
        "Лоб (большой)": "большой",      
    },
    "Волосы или шапка (аккуратность)": {
        "Волосы или шапка (нарисованы небрежно)": "нарисованы небрежно",
        "Волосы или шапка (нарисованы особо старательно)": "нарисованы особо старательно",     
    },
    "Кисть (размер)": {
        "Кисть (маленькая)": "маленькая",
        "Кисть (средняя (стандарт))": "средняя (стандарт)",
        "Кисть (большая)": "большая",    
    },
    "Ноги (одна или обе) (положение)": {
        "Ноги (одна или обе) (две ноги в одинаковом положении)": "две ноги в одинаковом положении",
        "Ноги (одна или обе) (две ноги в разном положении)": "две ноги в разном положении",       
    },
    "Ноги (постановка)": {
        "Ноги (сведены вместе)": "сведены вместе",
        "Ноги (слегка расставлены (стандарт))": "слегка расставлены (стандарт)",
        "Ноги (широко расставлены)": "широко расставлены",   
    },
    "Ноги (длина)": {
        "Ноги (короткие)": "короткие",
        "Ноги (длинные)": "длинные",
    },
    "Правая нога (положение)": {
        "Правая нога (вертикальна)": "вертикальна",
        "Правая нога (отставлена (стандарт))": "отставлена (стандарт)",
        "Правая нога (согнута)": "согнута",   
    },
    "Правая нога (длина)": {
        "Правая нога (короткая)": "короткая",
        "Правая нога (длинная)": "длинная",  
    },
    "Левая нога (положение)": {
        "Левая нога (вертикальна)": "вертикальна",
        "Левая нога (отставлена (стандарт))": "отставлена (стандарт)",
        "Левая нога (согнута)": "согнута",   
    },
    "Левая нога (длина)": {
        "Левая нога (короткая)": "короткая",
        "Левая нога (длинная)": "длинная",  
    },
    "Нога (положение)": {
        "Нога (вертикальна)": "вертикальна",
        "Нога (отставлена (стандарт))": "отставлена (стандарт)",
        "Нога (согнута)": "согнута",
    },
    "Нога (длина)": {
        "Нога (короткая)": "короткая",
        "Нога (длинная)": "длинная", 
    },
    "Ступни (размер)": {
        "Ступни (маленькие)": "маленькие",
        "Ступни (большие)": "большие",   
    },
    "Шея (размер)": {
        "Шея (тонкая)": "тонкая",
        "Шея (толстая)": "толстая",
    },
    "Тело (форма)": {
        "Тело (палочка)": "палочка",
        "Тело (округлое)": "округлое",
        "Тело (прямоугольное)": "прямоугольное",
        "Тело (треугольное)": "треугольное",
    },
    "Тело (размер)": {
        "Тело (вытянутое)": "вытянутое",
        "Тело (широкое)": "широкое",
    },
    "Пол персонажа": {
        "Пол (женский)": "женский",
        "Пол (мужской)": "мужской",
        "Пол (неопределенный)": "неопределенный",
    },
    "Одежда (способ изображения)": {
        "Одежда (реалистичное изображение)": "реалистичное изображение",
        "Одежда (условное изображение)": "условное изображение",
        "Одежда ('рентгеновский' рисунок)": "'рентгеновский' рисунок",
        "Одежда (отсутствует, тело изображено условно)": "отсутствует, тело изображено условно",
        "Одежда (отсутствует, человек обнажен)": "отсутствует, человек обнажен",
    },
}

In [143]:
old_shape = df.shape

In [144]:
merge_enabled = True

exception_groups = {
    "Ступни (размер)",
    "Шея (размер)",
    "Волосы или шапка (аккуратность)",
    "Левый глаз (форма)",
    "Лоб (размер)",
    "Ноги (постановка)",
    "Правая нога (положение)",
    "Левая нога (положение)",
}

merge_analysis = {}
mergeable_groups = []
not_mergeable_groups = []
exception_rows_to_drop = set()

for new_col, source_map in features_to_merge.items():
    source_cols = list(source_map.keys())
    missing_cols = [c for c in source_cols if c not in df.columns]

    if missing_cols:
        merge_analysis[new_col] = {
            "status": "missing_columns",
            "missing_columns": missing_cols,
            "source_columns": source_cols,
        }
        continue

    filled_counts = df[source_cols].notna().sum(axis=1)
    conflict_mask = filled_counts > 1
    conflict_rows = int(conflict_mask.sum())

    if conflict_rows > 0:
        if new_col in exception_groups:
            merge_analysis[new_col] = {
                "status": "exception_can_merge",
                "source_columns": source_cols,
                "conflict_rows": conflict_rows,
                "rows_to_drop": df.index[conflict_mask].tolist(),
            }
            mergeable_groups.append(new_col)
            exception_rows_to_drop.update(df.index[conflict_mask].tolist())
        else:
            merge_analysis[new_col] = {
                "status": "cannot_merge",
                "source_columns": source_cols,
                "conflict_rows": conflict_rows,
            }
            not_mergeable_groups.append(new_col)
    else:
        merge_analysis[new_col] = {
            "status": "can_merge",
            "source_columns": source_cols,
        }
        mergeable_groups.append(new_col)

print("Можно объединить:")
for group_name in mergeable_groups:
    status = merge_analysis[group_name]["status"]
    if status == "exception_can_merge":
        conflict_rows = merge_analysis[group_name]["conflict_rows"]
        print(f"- {group_name} (исключение, будет удалено строк: {conflict_rows})")
    else:
        print(f"- {group_name}")

print("\nНельзя объединить:")
for group_name in not_mergeable_groups:
    conflict_rows = merge_analysis[group_name]["conflict_rows"]
    print(f"- {group_name} (строк с 2+ заполненными признаками: {conflict_rows})")

print("\nИсключения:")
for group_name in exception_groups:
    if group_name in merge_analysis and merge_analysis[group_name]["status"] == "exception_can_merge":
        conflict_rows = merge_analysis[group_name]["conflict_rows"]
        print(f"- {group_name}: будет удалено строк {conflict_rows}")

print("\nПропущены (нет нужных столбцов в df):")
for group_name, info in merge_analysis.items():
    if info["status"] == "missing_columns":
        print(f"- {group_name}: {info['missing_columns']}")

if merge_enabled:
    if exception_rows_to_drop:
        before_drop_shape = df.shape
        df = df.drop(index=sorted(exception_rows_to_drop)).reset_index(drop=True)
        print(f"\nУдалены строки по исключениям: {len(exception_rows_to_drop)}")
        print(f"Форма df после удаления строк: {before_drop_shape} -> {df.shape}")

    for new_col in mergeable_groups:
        source_map = features_to_merge[new_col]
        source_cols = list(source_map.keys())

        merged_series = pd.Series(np.nan, index=df.index, dtype=object)
        for source_col, label in source_map.items():
            mask = df[source_col].notna() & merged_series.isna()
            if mask.any():
                merged_series.loc[mask] = label

        df[new_col] = merged_series
        df = df.drop(columns=source_cols)

    print(f"\nОбъединение выполнено. Новая форма df: {df.shape}")
else:
    print("\nФлаг merge_enabled=False, объединение не выполнялось.")

Можно объединить:
- Голова (размер)
- Левый глаз (форма) (исключение, будет удалено строк: 1)
- Правый глаз (форма)
- Лоб (размер) (исключение, будет удалено строк: 1)
- Волосы или шапка (аккуратность) (исключение, будет удалено строк: 8)
- Ноги (одна или обе) (положение)
- Ноги (постановка) (исключение, будет удалено строк: 1)
- Ноги (длина)
- Правая нога (положение) (исключение, будет удалено строк: 3)
- Правая нога (длина)
- Левая нога (положение) (исключение, будет удалено строк: 1)
- Левая нога (длина)
- Ступни (размер) (исключение, будет удалено строк: 2)
- Шея (размер) (исключение, будет удалено строк: 1)

Нельзя объединить:
- Глаза (форма) (строк с 2+ заполненными признаками: 20)
- Кисть (размер) (строк с 2+ заполненными признаками: 17)
- Тело (форма) (строк с 2+ заполненными признаками: 33)
- Тело (размер) (строк с 2+ заполненными признаками: 32)
- Пол персонажа (строк с 2+ заполненными признаками: 9)
- Одежда (способ изображения) (строк с 2+ заполненными признаками: 89)

Исключения:
- Лоб (размер): будет удалено строк 1
- Ноги (постановка): будет удалено строк 1
- Левая нога (положение): будет удалено строк 1
- Ступни (размер): будет удалено строк 2
- Шея (размер): будет удалено строк 1
- Правая нога (положение): будет удалено строк 3
- Волосы или шапка (аккуратность): будет удалено строк 8
- Левый глаз (форма): будет удалено строк 1

Пропущены (нет нужных столбцов в df):
- Нога (положение): ['Нога (отставлена (стандарт))', 'Нога (согнута)']
- Нога (длина): ['Нога (короткая)', 'Нога (длинная)']

Удалены строки по исключениям: 18
Форма df после удаления строк: (8448, 304) -> (8430, 304)

Объединение выполнено. Новая форма df: (8430, 282)

In [145]:
df

,Код-идентификатор обследуемого,Возраст обследуемого,Пол обследуемого,Расположение на листе (без особенностей),Расположение на листе (смещение вправо),Расположение на листе (смещение влево),Расположение на листе (смещение вверх),Расположение на листе (смещение вниз),Расположение на листе (размещение в углу),"Расположение на листе (изображение обрезано - есть место для дорисовки, но не дорисовано)",...,Волосы или шапка (аккуратность),Ноги (одна или обе) (положение),Ноги (постановка),Ноги (длина),Правая нога (положение),Правая нога (длина),Левая нога (положение),Левая нога (длина),Ступни (размер),Шея (размер)
0,ЧУВ6лм1кл_6,4-6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,нарисованы небрежно,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ЧУВ6лм1кл_5,4-6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ЧУВ6лм1кл_4,4-6,мужской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,две ноги в одинаковом положении,сведены вместе,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ЧУВ5лмдс_51,4-6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,нарисованы небрежно,две ноги в одинаковом положении,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ЧУВ5лмдс_50,4-6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8425,ЧУВ5лждс (79),4-6,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,NaN,NaN,NaN,NaN,тонкая
8426,ЧУВ5лждс (78),4-6,женский,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,NaN,NaN,NaN,NaN,тонкая
8427,ЧУВ5лждс (77),4-6,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,NaN,...,нарисованы особо старательно,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8428,ЧУВ5лждс (76),4-6,женский,без особенностей,NaN,NaN,NaN,NaN,NaN,NaN,...,нарисованы особо старательно,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,NaN,NaN,NaN,NaN,тонкая
8429,ЧУВ5лждс (75),4-6,женский,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,нарисованы особо старательно,две ноги в разном положении,NaN,NaN,вертикальна,NaN,отставлена (стандарт),NaN,NaN,NaN

In [146]:
df.shape, old_shape

((8430, 282), (8448, 304))

In [147]:
labels_to_merge = {
    "Размер рисунка": {
        "крупный": {
            "крупный",
            "очень крупный",
        },
        "мелкий": {
            "мелкий",
            "очень мелкий",
        }
    },
    "Аккуратность рисунка": {
        "низкая": {
            "низкая",
            "очень низкая",
        },
        "высокая": {
            "высокая",
            "очень высокая",
        },
    },
    "Детализированность": {
        "низкая": {
            "низкая",
            "очень низкая",
        },
        "высокая": {
            "высокая",
            "очень высокая",
        },
    },
    "Рот": {
        "маленький": {
            "маленький",
            "очень маленький",
        },
        "большой": {
            "большой",
            "очень большой",
        },
    },
}

In [148]:
label_merge_report = {}

for feature_name, merge_rules in labels_to_merge.items():
    if feature_name not in df.columns:
        label_merge_report[feature_name] = {
            "status": "missing_feature",
            "changed_rows": 0,
        }
        continue

    if not merge_rules:
        label_merge_report[feature_name] = {
            "status": "empty_rules",
            "changed_rows": 0,
        }
        continue

    value_to_target = {}
    for target_label, source_values in merge_rules.items():
        for value in source_values:
            value_to_target[value] = target_label

    before_values = df[feature_name].copy()
    df[feature_name] = df[feature_name].map(lambda x: value_to_target.get(x, x) if pd.notna(x) else x)

    changed_mask = (before_values != df[feature_name]) & ~(before_values.isna() & df[feature_name].isna())
    changed_rows = int(changed_mask.sum())

    label_merge_report[feature_name] = {
        "status": "merged",
        "changed_rows": changed_rows,
    }

print("Результаты объединения значений:")
for feature_name, info in label_merge_report.items():
    if info["status"] == "merged":
        print(f"- {feature_name}: изменено строк {info['changed_rows']}")
    elif info["status"] == "missing_feature":
        print(f"- {feature_name}: признак отсутствует в df")
    elif info["status"] == "empty_rules":
        print(f"- {feature_name}: правила объединения не заданы")

Результаты объединения значений:
- Размер рисунка: изменено строк 855
- Аккуратность рисунка: изменено строк 332
- Детализированность: изменено строк 565
- Рот: изменено строк 318

In [149]:
list(df.columns[1:])

['Возраст обследуемого',
 'Пол обследуемого',
 'Расположение на листе (без особенностей)',
 'Расположение на листе (смещение вправо)',
 'Расположение на листе (смещение влево)',
 'Расположение на листе (смещение вверх)',
 'Расположение на листе (смещение вниз)',
 'Расположение на листе (размещение в углу)',
 'Расположение на листе (изображение обрезано - есть место для дорисовки, но не дорисовано)',
 'Расположение на листе (изоброжение обрезано - обрезан краем листа / нет места для дорисовки)',
 'Степень смещения вправо',
 'Степень смещения влево',
 'Степень смещения вверх',
 'Степень смещения вниз',
 'Размещение в углу',
 'Что обрезано (голова)',
 'Что обрезано (одна рука)',
 'Что обрезано (обе руки)',
 'Что обрезано (ноги)',
 'Размер рисунка',
 'Ракурс',
 'Поза',
 'Фигура в движении',
 'Способ изображения',
 'Изображение персонажа',
 'Персонаж',
 'Нажим (без особенностей)',
 'Нажим (слабый)',
 'Нажим (сильный)',
 'Нажим (сильно варьирует)',
 'Особенности линии (без особенностей)',
 'Особенности линии (множественные)',
 'Особенности линии (эскизные)',
 "Особенности линии ('кусочные')",
 'Особенности линии (недоведенные)',
 "Особенности линии ('промахивающиеся')",
 'Особенности линии (другое)',
 'Множественные, степень выраженности',
 'Эскизные, степень выраженности',
 "'Кусочные', степень выраженности",
 'Недоведенные, степень выраженности',
 "'Промахивающиеся', степень выраженности",
 'Аккуратность рисунка',
 'Штриховка',
 'Нажим штриховки (без особенностей)',
 'Нажим штриховки (слабый)',
 'Нажим штриховки (сильный)',
 'Нажим штриховки (варьирует)',
 'Аккуратность штриховки (очень низкая)',
 'Аккуратность штриховки (низкая)',
 'Аккуратность штриховки (средняя (стандарт))',
 'Аккуратность штриховки (высокая)',
 'Аккуратность штриховки (очень высокая)',
 'Аккуратность штриховки (разные виды штриховок)',
 'Детализированность',
 'Стирания, исправления',
 'Устойчивость изображенного человека',
 'Грубые нарушения рисунка (отсутствуют)',
 'Грубые нарушения рисунка (отклонение от вертикали)',
 'Грубые нарушения рисунка (нарушение пропорций)',
 'Грубые нарушения рисунка (грубая асимметрия)',
 'Изображение в рамке',
 'Голова (без особенностей)',
 'Голова (искажена форма)',
 'Голова (зачерненная / заштрихованная)',
 'Голова (отсутствует)',
 'Детали (лицо) (глаза (один или оба))',
 'Детали (лицо) (нос)',
 'Детали (лицо) (рот)',
 'Детали (лицо) (уши)',
 'Детали (лицо) (лоб)',
 'Детали (лицо) (волосы (шапка))',
 'Детали (лицо) (другое)',
 'Детали (лицо) (отсутствуют все указанные выше пункты)',
 'Два глаза одинаковые',
 'Форма глаз (точка)',
 'Форма глаз (черточка)',
 'Форма глаз (круг)',
 'Форма глаз (овал, реалистичная форма)',
 "Форма глаз ('мультяшные')",
 'Форма глаз (форма искажена)',
 'Форма глаз (отсутствуют)',
 "Форма левого глаза ('мультяшные')",
 'Форма левого глаза (форма искажена)',
 'Форма левого глаза (отсутствует)',
 "Форма правого глаза ('мультяшные')",
 'Форма правого глаза (форма искажена)',
 'Форма правого глаза (отсутствует)',
 'Размер глаз',
 'Размер левого глаза',
 'Размер правого глаза',
 'Дополнительные особенности глаз (без особенностей)',
 'Дополнительные особенности глаз (подчеркнутый контур)',
 "Дополнительные особенности глаз ('пустые')",
 'Дополнительные особенности глаз (зачернена радужка или весь глаз)',
 'Дополнительные особенности глаз (один или оба глаза закрыты волосами или шапкой)',
 'Дополнительные особенности глаз (изображены очки (прозрачные))',
 'Дополнительные особенности глаз (изображены темные очки)',
 'Дополнительные особенности глаз (закрыты)',
 'Дополнительные особенности глаз (полузакрыты (прищур))',
 'Дополнительные особенности правого глаза (без особенностей)',
 'Дополнительные особенности правого глаза (подчеркнутый контур)',
 "Дополнительные особенности правого глаза ('пустые')",
 'Дополнительные особенности правого глаза (зачернена радужка или весь глаз)',
 'Дополнительные особенности правого глаза (закрыт волосами или шапкой)',
 'Дополнительные особенности правого глаза (изображены очки (прозрачные))',
 'Дополнительные особенности правого глаза (закрыт)',
 'Дополнительные особенности правого глаза (полузакрыт (прищур))',
 'Дополнительные особенности левого глаза (без особенностей)',
 'Дополнительные особенности левого глаза (подчеркнутый контур)',
 "Дополнительные особенности левого глаза ('пустые')",
 'Дополнительные особенности левого глаза (зачернена радужка или весь глаз)',
 'Дополнительные особенности левого глаза (закрыт волосами или шапкой)',
 'Дополнительные особенности левого глаза (изображены очки (прозрачные))',
 'Дополнительные особенности левого глаза (изображены темные очки)',
 'Дополнительные особенности левого глаза (закрыт)',
 'Дополнительные особенности левого глаза (полузакрыт (прищур))',
 'Ресницы',
 'Нос (без особенностей)',
 'Нос (увеличен размер)',
 'Нос (усилен нажим)',
 'Нос (другое)',
 'Нос (отсутствует)',
 'Рот',
 'Форма рта',
 'Положение рта / губ',
 'Зубы',
 'Язык',
 'Уши (без особенностей)',
 'Уши (усилен нажим)',
 'Уши (преувеличен размер)',
 'Уши (другое)',
 'Уши (отсутствуют)',
 'Лоб (скрыт волосами или шапкой)',
 'Лоб (скрыт волосами, усилен нажим)',
 'Лоб (другое)',
 'Лоб (отсутствует)',
 'Волосы или шапка (без особенностей)',
 'Волосы или шапка (другое)',
 'Волосы или шапка (отсутствуют)',
 'Дополнительные детали на лице (брови)',
 'Дополнительные детали на лице (усы и / или борода)',
 'Дополнительные детали на лице (морщины)',
 'Дополнительные детали на лице (маска)',
 'Дополнительные детали на лице (рисунки на лице)',
 'Дополнительные детали на лице (другое)',
 'Дополнительные детали на лице (отсутствуют)',
 'Руки (одна или обе)',
 'Положение рук (слегка отставлены (стандарт))',
 'Положение рук (прижаты к телу (от верха до локтя))',
 'Положение рук (свободно опущены)',
 'Положение рук (сильно отставлены)',
 'Положение рук (вытянуты в стороны или вперед)',
 'Положение рук (подняты)',
 'Положение рук (дополнительно)',
 'Положение рук (за спиной или в карманах)',
 'Положение рук (на фоне тела)',
 'Положение рук (скрещены на груди)',
 'Положение рук (уперты в бока)',
 'Положение рук (закрывают генитальную область)',
 'Положение рук (прижаты к голове)',
 'Положение рук (другое)',
 'Положение правой руки',
 'Положение правой руки.1',
 'Положение левой руки',
 'Положение левой руки.1',
 'Положение руки (слегка отставлена (стандарт))',
 'Положение руки (прижата к телу (от верха до локтя))',
 'Положение руки (свободно опущена)',
 'Положение руки (сильно отставлена)',
 'Положение руки (вытянута в сторону или вперед)',
 'Положение руки (поднята)',
 'Положение руки (дополнительно)',
 'Положение руки (за спиной или в кармане)',
 'Положение руки (на фоне тела)',
 'Положение руки (уперта в бок)',
 'Положение руки (другое)',
 'Кисть (маленькая)',
 'Кисть (средняя (стандарт))',
 'Кисть (большая)',
 'Кисть (повышен нажим)',
 'Кисть (зачернена)',
 'Кисть (отсутствует)',
 'Ладонь, пальцы (изображены пальцы)',
 'Ладонь, пальцы (изображена ладонь)',
 "Ладонь, пальцы (положение 'варежки')",
 'Ладонь, пальцы (кулак, большой палец снаружи)',
 'Ладонь, пальцы (кулак, большой палец не виден)',
 'Ладонь, пальцы (отсутствуют)',
 'Пальцы (изображены черточками)',
 'Пальцы (передана толщина)',
 'Пальцы (округлые ногти)',
 'Пальцы (заостренные ногти)',
 'Пальцы (другое)',
 'Ноги (одна или обе) (только одна нога)',
 'Ноги (одна или обе) (скрыты препятствием)',
 'Ноги (одна или обе) (отсутствуют)',
 'Ноги (другое)',
 'Правая нога (другое)',
 'Левая нога (другое)',
 'Нога (вертикальна)',
 'Нога (другое)',
 'Ступни (без особенностей)',
 'Ступни (повышен нажим)',
 'Ступни (зачернены)',
 'Ступни (отсутствуют)',
 'Ступни (другое)',
 'Шея (без особенностей)',
 'Шея (одинарная линия)',
 'Шея (короткая)',
 'Шея (длинная)',
 'Шея (отсутствует)',
 'Тело (палочка)',
 'Тело (округлое)',
 'Тело (прямоугольное)',
 'Тело (реалистичное)',
 'Тело (вытянутое)',
 'Тело (широкое)',
 'Тело (отсутствует)',
 'Тело (треугольное)',
 'Тело (другое)',
 'Пол (женский)',
 'Пол (мужской)',
 'Пол (неопределенный)',
 'Пол (признаки пола подчеркнуты)',
 'Пол (подчеркнута генитальная область)',
 'Пол (изображены половые органы)',
 'Одежда (реалистичное изображение)',
 'Одежда (условное изображение)',
 "Одежда ('рентгеновский' рисунок)",
 'Одежда (отсутствует, тело изображено условно)',
 'Одежда (отсутствует, человек обнажен)',
 'Дополнительные детали изображения фигуры (отсутствуют)',
 'Дополнительные детали изображения фигуры (пуговицы)',
 'Дополнительные детали изображения фигуры (пуп)',
 'Дополнительные детали изображения фигуры (ширинка)',
 'Дополнительные детали изображения фигуры (волосы на теле или конечностях)',
 'Дополнительные детали изображения фигуры (украшения)',
 'Дополнительные детали изображения фигуры (другое)',
 'Дополнительные детали изображения фигуры (ремень / пояс)',
 'Пуговицы',
 'Украшения, узор на одежде',
 'Дополнительно (в руке или рядом) (игрушка, шарик)',
 'Дополнительно (в руке или рядом) (цветок)',
 'Дополнительно (в руке или рядом) (животное)',
 'Дополнительно (в руке или рядом) (палка)',
 'Дополнительно (в руке или рядом) (меч, нож, топор)',
 'Дополнительно (в руке или рядом) (пистолет, ружье)',
 'Дополнительно (в руке или рядом) (шприц)',
 'Дополнительно (в руке или рядом) (сигарета)',
 'Дополнительно (в руке или рядом) (сумка)',
 'Дополнительно (в руке или рядом) (телефон)',
 'Дополнительно (в руке или рядом) (зонт)',
 'Дополнительно (в руке или рядом) (дополнительные предметы отсутствуют)',
 'Фон (отсутствует)',
 'Фон (штриховка)',
 'Фон (опорная линия)',
 'Фон (заштрихованное облако)',
 'Фон (пейзаж)',
 'Фон (пейзаж преобладает над изображением человека)',
 'Фон (дождь)',
 'Фон (солнце)',
 'Фон (земля)',
 'Фон (другое)',
 'Площадь штриховки',
 'Нажим',
 'Шея отделена от тела линией',
 'Голова (размер)',
 'Левый глаз (форма)',
 'Правый глаз (форма)',
 'Лоб (размер)',
 'Волосы или шапка (аккуратность)',
 'Ноги (одна или обе) (положение)',
 'Ноги (постановка)',
 'Ноги (длина)',
 'Правая нога (положение)',
 'Правая нога (длина)',
 'Левая нога (положение)',
 'Левая нога (длина)',
 'Ступни (размер)',
 'Шея (размер)']

In [150]:
bad_features = [
    # ========== 1 ==========
    # "Возраст обследуемого",
    # "Пол обследуемого",
    # "Расположение на листе (без особенностей)",
    # "Расположение на листе (смещение вправо)",

    # "Расположение на листе (смещение влево)",
    # "Расположение на листе (смещение вверх)",
    # "Расположение на листе (смещение вниз)",
    "Расположение на листе (размещение в углу)",

    "Расположение на листе (изображение обрезано - есть место для дорисовки, но не дорисовано)",
    # "Расположение на листе (изоброжение обрезано - обрезан краем листа / нет места для дорисовки)",
    # "Степень смещения вправо",
    # "Степень смещения влево",

    # "Степень смещения вверх",
    # "Степень смещения вниз",
    "Размещение в углу",
    "Что обрезано (голова)",

    # ========== 2 ==========
    "Что обрезано (одна рука)",
    "Что обрезано (обе руки)",
    "Что обрезано (ноги)",
    # "Размер рисунка",

    # "Ракурс",
    # "Поза",
    # "Фигура в движении",
    # "Способ изображения",

    # "Изображение персонажа",
    "Персонаж",
    # "Нажим (без особенностей)",
    # "Нажим (слабый)",

    # "Нажим (сильный)",
    # "Нажим (сильно варьирует)",
    # "Особенности линии (без особенностей)",
    # "Особенности линии (множественные)",

    # ========== 3 ==========
    # "Особенности линии (эскизные)",
    # "Особенности линии ('кусочные')",
    # "Особенности линии (недоведенные)",
    # "Особенности линии ('промахивающиеся')",

    "Особенности линии (другое)",
    # "Множественные, степень выраженности",
    # "Эскизные, степень выраженности",
    # "'Кусочные', степень выраженности",

    "Недоведенные, степень выраженности",
    # "'Промахивающиеся', степень выраженности",
    # "Аккуратность рисунка",
    # "Штриховка",

    # "Нажим штриховки (без особенностей)",
    # "Нажим штриховки (слабый)",
    # "Нажим штриховки (сильный)",
    # "Нажим штриховки (варьирует)",

    # ========== 4 ==========
    "Аккуратность штриховки (очень низкая)",
    # "Аккуратность штриховки (низкая)",
    # "Аккуратность штриховки (средняя (стандарт))",
    "Аккуратность штриховки (высокая)",
    
    "Аккуратность штриховки (очень высокая)",
    "Аккуратность штриховки (разные виды штриховок)",
    # "Детализированность",
    # "Стирания, исправления",

    # "Устойчивость изображенного человека",
    # "Грубые нарушения рисунка (отсутствуют)",
    # "Грубые нарушения рисунка (отклонение от вертикали)",
    # "Грубые нарушения рисунка (нарушение пропорций)",

    "Грубые нарушения рисунка (грубая асимметрия)",
    # "Изображение в рамке",
    # "Голова (без особенностей)",
    # "Голова (искажена форма)",
    
    # ========== 5 ==========
    "Голова (зачерненная / заштрихованная)",
    "Голова (отсутствует)",
    # "Детали (лицо) (глаза (один или оба))",
    # "Детали (лицо) (нос)",

    # "Детали (лицо) (рот)",
    # "Детали (лицо) (уши)",
    # "Детали (лицо) (лоб)",
    # "Детали (лицо) (волосы (шапка))",

    # "Детали (лицо) (другое)",
    "Детали (лицо) (отсутствуют все указанные выше пункты)",
    # "Два глаза одинаковые",
    # "Форма глаз (точка)",

    # "Форма глаз (черточка)",
    # "Форма глаз (круг)",
    # "Форма глаз (овал, реалистичная форма)",
    # "Форма глаз ('мультяшные')",

    # ========== 6 ==========
    "Форма глаз (форма искажена)",
    "Форма глаз (отсутствуют)",
    "Форма левого глаза ('мультяшные')",
    "Форма левого глаза (форма искажена)",

    "Форма левого глаза (отсутствует)",
    "Форма правого глаза ('мультяшные')",
    "Форма правого глаза (форма искажена)",
    "Форма правого глаза (отсутствует)",

    # "Размер глаз",
    "Размер левого глаза",
    "Размер правого глаза",
    # "Дополнительные особенности глаз (без особенностей)",

    # "Дополнительные особенности глаз (подчеркнутый контур)",
    # "Дополнительные особенности глаз ('пустые')",
    # "Дополнительные особенности глаз (зачернена радужка или весь глаз)",
    "Дополнительные особенности глаз (один или оба глаза закрыты волосами или шапкой)",

    # ========== 7 ==========
    "Дополнительные особенности глаз (изображены очки (прозрачные))",
    "Дополнительные особенности глаз (изображены темные очки)",
    # "Дополнительные особенности глаз (закрыты)",
    "Дополнительные особенности глаз (полузакрыты (прищур))",

    "Дополнительные особенности правого глаза (без особенностей)",
    "Дополнительные особенности правого глаза (подчеркнутый контур)",
    "Дополнительные особенности правого глаза ('пустые')",
    "Дополнительные особенности правого глаза (зачернена радужка или весь глаз)",

    "Дополнительные особенности правого глаза (закрыт волосами или шапкой)",
    "Дополнительные особенности правого глаза (изображены очки (прозрачные))",
    "Дополнительные особенности правого глаза (закрыт)",
    "Дополнительные особенности правого глаза (полузакрыт (прищур))",

    "Дополнительные особенности левого глаза (без особенностей)",
    "Дополнительные особенности левого глаза (подчеркнутый контур)",
    "Дополнительные особенности левого глаза ('пустые')",
    "Дополнительные особенности левого глаза (зачернена радужка или весь глаз)",

    # ========== 8 ==========
    "Дополнительные особенности левого глаза (закрыт волосами или шапкой)",
    "Дополнительные особенности левого глаза (изображены очки (прозрачные))",
    "Дополнительные особенности левого глаза (изображены темные очки)",
    "Дополнительные особенности левого глаза (закрыт)",

    "Дополнительные особенности левого глаза (полузакрыт (прищур))",
    # "Ресницы",
    # "Нос (без особенностей)",
    # "Нос (увеличен размер)",

    # "Нос (усилен нажим)",
    "Нос (другое)",
    "Нос (отсутствует)",
    # "Рот",

    # "Форма рта",
    # "Положение рта / губ",
    # "Зубы",
    # "Язык",

    # ========== 9 ==========
    # "Уши (без особенностей)",
    "Уши (усилен нажим)",
    # "Уши (преувеличен размер)",
    "Уши (другое)",
    
    "Уши (отсутствуют)",
    # "Лоб (скрыт волосами или шапкой)",
    "Лоб (скрыт волосами, усилен нажим)",
    "Лоб (другое)",

    "Лоб (отсутствует)",
    # "Волосы или шапка (без особенностей)",
    "Волосы или шапка (другое)",
    "Волосы или шапка (отсутствуют)",

    # "Дополнительные детали на лице (брови)",
    # "Дополнительные детали на лице (усы и / или борода)",
    "Дополнительные детали на лице (морщины)",
    "Дополнительные детали на лице (маска)",

    # ========== 10 ==========
    "Дополнительные детали на лице (рисунки на лице)",
    # "Дополнительные детали на лице (другое)",
    # "Дополнительные детали на лице (отсутствуют)",
    # "Руки (одна или обе)",

    # "Положение рук (слегка отставлены (стандарт))",
    # "Положение рук (прижаты к телу (от верха до локтя))",
    # "Положение рук (свободно опущены)",
    # "Положение рук (сильно отставлены)",

    # "Положение рук (вытянуты в стороны или вперед)",
    # "Положение рук (подняты)",
    # "Положение рук (дополнительно)",
    # "Положение рук (за спиной или в карманах)",

    "Положение рук (на фоне тела)",
    "Положение рук (скрещены на груди)",
    "Положение рук (уперты в бока)",
    "Положение рук (закрывают генитальную область)",

    # ========== 11 ==========
    "Положение рук (прижаты к голове)",
    "Положение рук (другое)",
    "Положение правой руки",
    "Положение правой руки.1",

    "Положение левой руки",
    "Положение левой руки.1",
    "Положение руки (слегка отставлена (стандарт))",
    "Положение руки (прижата к телу (от верха до локтя))",

    "Положение руки (свободно опущена)",
    "Положение руки (сильно отставлена)",
    "Положение руки (вытянута в сторону или вперед)",
    "Положение руки (поднята)",

    "Положение руки (дополнительно)",
    "Положение руки (за спиной или в кармане)",
    "Положение руки (на фоне тела)",
    "Положение руки (уперта в бок)",

    # ========== 12 ==========
    "Положение руки (другое)",
    # "Кисть (маленькая)",
    # "Кисть (средняя (стандарт))",
    # "Кисть (большая)",
    
    "Кисть (повышен нажим)",
    "Кисть (зачернена)",
    # "Кисть (отсутствует)",
    # "Ладонь, пальцы (изображены пальцы)",

    # "Ладонь, пальцы (изображена ладонь)",
    # "Ладонь, пальцы (положение 'варежки')",
    "Ладонь, пальцы (кулак, большой палец снаружи)",
    "Ладонь, пальцы (кулак, большой палец не виден)",

    # "Ладонь, пальцы (отсутствуют)",
    # "Пальцы (изображены черточками)",
    # "Пальцы (передана толщина)",
    "Пальцы (округлые ногти)",

    # ========== 13 ==========
    "Пальцы (заостренные ногти)",
    "Пальцы (другое)",
    "Ноги (одна или обе) (только одна нога)",
    "Ноги (одна или обе) (скрыты препятствием)",

    "Ноги (одна или обе) (отсутствуют)",
    "Ноги (другое)",
    "Правая нога (другое)",
    "Левая нога (другое)",

    "Нога (вертикальна)",
    "Нога (другое)",
    # "Ступни (без особенностей)",
    "Ступни (повышен нажим)",
    
    # "Ступни (зачернены)",
    # "Ступни (отсутствуют)",
    "Ступни (другое)",
    # "Шея (без особенностей)",

    # ========== 14 ==========
    "Шея (одинарная линия)",
    # "Шея (короткая)",
    # "Шея (длинная)",
    # "Шея (отсутствует)",

    "Тело (палочка)",
    # "Тело (округлое)",
    # "Тело (прямоугольное)",
    # "Тело (реалистичное)",

    # "Тело (вытянутое)",
    # "Тело (широкое)",
    "Тело (отсутствует)",
    # "Тело (треугольное)",

    "Тело (другое)",
    # "Пол (женский)",
    # "Пол (мужской)",
    # "Пол (неопределенный)",

    # ========== 15 ==========
    # "Пол (признаки пола подчеркнуты)",
    # "Пол (подчеркнута генитальная область)",
    "Пол (изображены половые органы)",
    # "Одежда (реалистичное изображение)",

    # "Одежда (условное изображение)",
    # "Одежда ('рентгеновский' рисунок)",
    # "Одежда (отсутствует, тело изображено условно)",
    "Одежда (отсутствует, человек обнажен)",

    # "Дополнительные детали изображения фигуры (отсутствуют)",
    # "Дополнительные детали изображения фигуры (пуговицы)",
    # "Дополнительные детали изображения фигуры (пуп)",
    "Дополнительные детали изображения фигуры (ширинка)",
    
    "Дополнительные детали изображения фигуры (волосы на теле или конечностях)",
    # "Дополнительные детали изображения фигуры (украшения)",
    # "Дополнительные детали изображения фигуры (другое)",
    # "Дополнительные детали изображения фигуры (ремень / пояс)",
    
    # ========== 16 ==========
    # "Пуговицы",
    # "Украшения, узор на одежде",
    "Дополнительно (в руке или рядом) (игрушка, шарик)",
    "Дополнительно (в руке или рядом) (цветок)",

    "Дополнительно (в руке или рядом) (животное)",
    "Дополнительно (в руке или рядом) (палка)",
    "Дополнительно (в руке или рядом) (меч, нож, топор)",
    "Дополнительно (в руке или рядом) (пистолет, ружье)",

    "Дополнительно (в руке или рядом) (шприц)",
    "Дополнительно (в руке или рядом) (сигарета)",
    "Дополнительно (в руке или рядом) (сумка)",
    "Дополнительно (в руке или рядом) (телефон)",

    "Дополнительно (в руке или рядом) (зонт)",
    # "Дополнительно (в руке или рядом) (дополнительные предметы отсутствуют)",
    # "Фон (отсутствует)",
    "Фон (штриховка)",

    # ========== 17 ==========
    # "Фон (опорная линия)",
    "Фон (заштрихованное облако)",
    "Фон (пейзаж)",
    "Фон (пейзаж преобладает над изображением человека)",

    "Фон (дождь)",
    # "Фон (солнце)",
    # "Фон (земля)",
    "Фон (другое)",

    "Площадь штриховки",
    "Нажим",
    # "Шея отделена от тела линией",
    # "Голова (размер)",

    "Левый глаз (форма)",
    "Правый глаз (форма)",
    # "Лоб (размер)",
    # "Волосы или шапка (аккуратность)",

    # ========== 18 ==========
    # "Ноги (одна или обе) (положение)",
    # "Ноги (постановка)",
    # "Ноги (длина)",
    "Правая нога (положение)",

    "Правая нога (длина)",
    "Левая нога (положение)",
    "Левая нога (длина)",
    # "Ступни (размер)",

    # "Шея (размер)",
]

In [151]:
missing_bad_features = [col for col in bad_features if col not in df.columns]
if missing_bad_features:
    raise KeyError(f"Не найдены столбцы из bad_features: {missing_bad_features}")

df = df.drop(columns=bad_features)
print(f"Удалено столбцов из bad_features: {len(bad_features)}")
print(f"Текущая форма df: {df.shape}")

Удалено столбцов из bad_features: 133
Текущая форма df: (8430, 149)

In [152]:
df

,Код-идентификатор обследуемого,Возраст обследуемого,Пол обследуемого,Расположение на листе (без особенностей),Расположение на листе (смещение вправо),Расположение на листе (смещение влево),Расположение на листе (смещение вверх),Расположение на листе (смещение вниз),Расположение на листе (изоброжение обрезано - обрезан краем листа / нет места для дорисовки),Степень смещения вправо,...,Фон (земля),Шея отделена от тела линией,Голова (размер),Лоб (размер),Волосы или шапка (аккуратность),Ноги (одна или обе) (положение),Ноги (постановка),Ноги (длина),Ступни (размер),Шея (размер)
0,ЧУВ6лм1кл_6,4-6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,шея отсутствует,NaN,NaN,нарисованы небрежно,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN
1,ЧУВ6лм1кл_5,4-6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,шея отсутствует,NaN,средний (стандарт),NaN,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN
2,ЧУВ6лм1кл_4,4-6,мужской,NaN,NaN,NaN,NaN,NaN,изоброжение обрезано - обрезан краем листа / н...,NaN,...,NaN,шея отсутствует,NaN,средний (стандарт),NaN,две ноги в одинаковом положении,сведены вместе,NaN,NaN,NaN
3,ЧУВ5лмдс_51,4-6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,шея отсутствует,NaN,NaN,нарисованы небрежно,две ноги в одинаковом положении,NaN,NaN,NaN,NaN
4,ЧУВ5лмдс_50,4-6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,шея отсутствует,маленькая,средний (стандарт),NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8425,ЧУВ5лждс (79),4-6,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,незначительно,...,земля,ничего из перечисленного,NaN,средний (стандарт),NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,тонкая
8426,ЧУВ5лждс (78),4-6,женский,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,просто линия,большая,NaN,NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,тонкая
8427,ЧУВ5лждс (77),4-6,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,незначительно,...,NaN,ничего из перечисленного,NaN,маленький,нарисованы особо старательно,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN
8428,ЧУВ5лждс (76),4-6,женский,без особенностей,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,просто линия,NaN,маленький,нарисованы особо старательно,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,тонкая
8429,ЧУВ5лждс (75),4-6,женский,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,ничего из перечисленного,NaN,средний (стандарт),нарисованы особо старательно,две ноги в разном положении,NaN,NaN,NaN,NaN

In [153]:
statistics = []

for col_idx in range(1, len(df.columns)):
    col_name = df.columns[col_idx]
    column_data = df[col_name]
    
    missing_count = int(column_data.isna().sum())
    
    value_counts = column_data.value_counts(dropna=False)
    
    stat_row = {
        'features': col_name,
        'unique_values': [],
        'frequencies': [],
        'missing_values': missing_count
    }
    
    has_empty = False
    for value, count in value_counts.items():
        value_str = str(value)
        if pd.isna(value) or value_str.lower() == 'nan':
            value_str = 'пусто'
            has_empty = True
        stat_row['unique_values'].append(value_str)
        stat_row['frequencies'].append(int(count))

    if missing_count > 0 and not has_empty:
        stat_row['unique_values'].append('пусто')
        stat_row['frequencies'].append(missing_count)

    statistics.append(stat_row)

In [154]:
prefix = "4_1"

In [155]:
analysis_dir = f"./{prefix}_analysis"
os.makedirs(analysis_dir, exist_ok=True)

output_file = f"{analysis_dir}/{prefix}_statistics_analysis.xlsx"

max_unique_values = max(len(stat['unique_values']) for stat in statistics)

wb = Workbook()
ws = wb.active
ws.title = "Статистика признаков"

headers = ['Признак']
for i in range(max_unique_values):
    headers.append(f'Значение_{i+1}')
    headers.append(f'Частота_{i+1}')
headers.append('Пропуски')

cell_font = Font(bold=False)
cell_align = Alignment(horizontal='left', vertical='center')

for col_idx, header in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col_idx, value=header)
    cell.font = cell_font
    cell.alignment = cell_align

for row_idx, stat in enumerate(statistics, 2):
    col_idx = 1
    
    c = ws.cell(row=row_idx, column=col_idx, value=stat['features'])
    c.font = cell_font
    c.alignment = cell_align
    col_idx += 1
    
    unique_values = stat['unique_values']
    frequencies = stat['frequencies']
    
    for i in range(max_unique_values):
        if i < len(unique_values):
            uv = unique_values[i]
            if isinstance(uv, str) and uv != 'пусто':
                try:
                    f = float(uv)
                    if f.is_integer():
                        uv = int(f)
                except ValueError:
                    pass
            c = ws.cell(row=row_idx, column=col_idx, value=uv)
            c.font = cell_font
            c.alignment = cell_align
            col_idx += 1
            c = ws.cell(row=row_idx, column=col_idx, value=int(frequencies[i]))
            c.font = cell_font
            c.alignment = cell_align
            col_idx += 1
        else:
            col_idx += 2
    
    c = ws.cell(row=row_idx, column=col_idx, value=int(stat['missing_values']))
    c.font = cell_font
    c.alignment = cell_align

for col in ws.columns:
    max_length = 0
    col_letter = col[0].column_letter
    for cell in col:
        try:
            if cell.value:
                max_length = max(max_length, len(str(cell.value)))
        except:
            pass
    adjusted_width = min(max_length + 2, 50)
    ws.column_dimensions[col_letter].width = adjusted_width

wb.save(output_file)

In [156]:
reports_dir = os.path.join(analysis_dir, f"{prefix}_reports")
os.makedirs(reports_dir, exist_ok=True)

output_file = f"{reports_dir}/{prefix}_statistics_analysis.xlsx"

plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

rows_per_page = 4
cols_per_page = 4
graphs_per_page = rows_per_page * cols_per_page

total_features = len(statistics)
num_pages = math.ceil(total_features / graphs_per_page)

for page in range(num_pages):
    start_idx = page * graphs_per_page
    end_idx = min(start_idx + graphs_per_page, total_features)
    page_features = statistics[start_idx:end_idx]
    
    fig, axes = plt.subplots(rows_per_page, cols_per_page, figsize=(20, 16))
    axes = axes.flatten() if rows_per_page > 1 else [axes] if cols_per_page == 1 else axes
    
    for idx, stat in enumerate(page_features):
        ax = axes[idx]
        
        feature_name = stat['features']; # print(feature_name)
        values = stat['unique_values']; # print(values)
        counts = stat['frequencies']; # print(counts)
        
        if len(values) > 0:
            empty_color = '#CCCCCC'
            non_empty_values = [v for v in values if str(v).lower() != 'пусто']
            num_non_empty = len(non_empty_values)
            
            colors = []
            palette = sns.color_palette("husl", max(num_non_empty, 1))
            palette_idx = 0
            
            for v in values:
                if str(v).lower() == 'пусто':
                    colors.append(empty_color)
                else:
                    colors.append(palette[palette_idx % len(palette)])
                    palette_idx += 1
            
            bars = ax.bar(range(len(values)), counts, 
                         color=colors, 
                         alpha=0.7, edgecolor='black')
            
            ax.set_xticks(range(len(values)))
            labels = []
            for v in values:
                v_str = str(v)
                if v_str.lower() in ['nan', 'missing']:
                    v_str = 'пусто'
                labels.append(v_str[:25] + '...' if len(v_str) > 25 else v_str)
            ax.set_xticklabels(labels, rotation=45, ha='right', fontsize=8)
            ax.set_ylabel('Частота', fontsize=10)
            
            title = feature_name[:70] + '...' if len(feature_name) > 70 else feature_name
            ax.set_title(title, fontsize=9, fontweight='bold', pad=5)
            
            ax.grid(True, alpha=0.3, axis='y')
            
            for i, count in enumerate(counts):
                ax.text(i, count, str(count), ha='center', va='bottom', fontsize=7)
        else:
            ax.text(0.5, 0.5, 'Нет данных', ha='center', va='center', 
                   transform=ax.transAxes, fontsize=12)
            ax.set_title(feature_name[:70] + '...' if len(feature_name) > 70 else feature_name, 
                        fontsize=9, fontweight='bold')
            ax.axis('off')
    
    for idx in range(len(page_features), graphs_per_page):
        axes[idx].axis('off')
    
    plt.suptitle(f'Страница {page + 1} из {num_pages}', 
                 fontsize=16, fontweight='bold', y=0.995)
    plt.tight_layout(rect=[0, 0, 1, 0.99])
    
    output_file = f"{reports_dir}/{prefix}_all_feats_distrs_{page + 1}.png"
    plt.savefig(output_file, dpi=200, bbox_inches='tight')
    plt.close()
    
    print(output_file)

./4_1_analysis/4_1_reports/4_1_all_feats_distrs_1.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_2.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_3.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_4.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_5.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_6.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_7.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_8.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_9.png
./4_1_analysis/4_1_reports/4_1_all_feats_distrs_10.png

In [157]:
df.to_excel(f"{prefix}_features_transformation_and_merging.xlsx", index=False)