In [14]:
import math
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment

In [15]:
prefix = "4_1"

In [16]:
labels_path = f"./{prefix}_feature_selection_and_transformation.xlsx"
df = pd.read_excel(labels_path)
df.shape

(8430, 149)

In [17]:
df

,Код-идентификатор обследуемого,Возраст обследуемого,Пол обследуемого,Расположение на листе (без особенностей),Расположение на листе (смещение вправо),Расположение на листе (смещение влево),Расположение на листе (смещение вверх),Расположение на листе (смещение вниз),Расположение на листе (изоброжение обрезано - обрезан краем листа / нет места для дорисовки),Степень смещения вправо,...,Фон (земля),Шея отделена от тела линией,Голова (размер),Лоб (размер),Волосы или шапка (аккуратность),Ноги (одна или обе) (положение),Ноги (постановка),Ноги (длина),Ступни (размер),Шея (размер)
0,ЧУВ6лм1кл_6,4-6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,шея отсутствует,NaN,NaN,нарисованы небрежно,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN
1,ЧУВ6лм1кл_5,4-6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,шея отсутствует,NaN,средний (стандарт),NaN,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN
2,ЧУВ6лм1кл_4,4-6,мужской,NaN,NaN,NaN,NaN,NaN,изоброжение обрезано - обрезан краем листа / н...,NaN,...,NaN,шея отсутствует,NaN,средний (стандарт),NaN,две ноги в одинаковом положении,сведены вместе,NaN,NaN,NaN
3,ЧУВ5лмдс_51,4-6,мужской,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,шея отсутствует,NaN,NaN,нарисованы небрежно,две ноги в одинаковом положении,NaN,NaN,NaN,NaN
4,ЧУВ5лмдс_50,4-6,мужской,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,шея отсутствует,маленькая,средний (стандарт),NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8425,ЧУВ5лждс (79),4-6,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,незначительно,...,земля,ничего из перечисленного,NaN,средний (стандарт),NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,тонкая
8426,ЧУВ5лждс (78),4-6,женский,NaN,NaN,смещение влево,NaN,NaN,NaN,NaN,...,NaN,просто линия,большая,NaN,NaN,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,тонкая
8427,ЧУВ5лждс (77),4-6,женский,NaN,смещение вправо,NaN,NaN,смещение вниз,NaN,незначительно,...,NaN,ничего из перечисленного,NaN,маленький,нарисованы особо старательно,две ноги в одинаковом положении,широко расставлены,NaN,NaN,NaN
8428,ЧУВ5лждс (76),4-6,женский,без особенностей,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,просто линия,NaN,маленький,нарисованы особо старательно,две ноги в одинаковом положении,слегка расставлены (стандарт),NaN,NaN,тонкая
8429,ЧУВ5лждс (75),4-6,женский,NaN,NaN,NaN,NaN,смещение вниз,NaN,NaN,...,NaN,ничего из перечисленного,NaN,средний (стандарт),нарисованы особо старательно,две ноги в разном положении,NaN,NaN,NaN,NaN

In [18]:
list(df.columns)

['Код-идентификатор обследуемого',
 'Возраст обследуемого',
 'Пол обследуемого',
 'Расположение на листе (без особенностей)',
 'Расположение на листе (смещение вправо)',
 'Расположение на листе (смещение влево)',
 'Расположение на листе (смещение вверх)',
 'Расположение на листе (смещение вниз)',
 'Расположение на листе (изоброжение обрезано - обрезан краем листа / нет места для дорисовки)',
 'Степень смещения вправо',
 'Степень смещения влево',
 'Степень смещения вверх',
 'Степень смещения вниз',
 'Размер рисунка',
 'Ракурс',
 'Поза',
 'Фигура в движении',
 'Способ изображения',
 'Изображение персонажа',
 'Нажим (без особенностей)',
 'Нажим (слабый)',
 'Нажим (сильный)',
 'Нажим (сильно варьирует)',
 'Особенности линии (без особенностей)',
 'Особенности линии (множественные)',
 'Особенности линии (эскизные)',
 "Особенности линии ('кусочные')",
 'Особенности линии (недоведенные)',
 "Особенности линии ('промахивающиеся')",
 'Множественные, степень выраженности',
 'Эскизные, степень выраженности',
 "'Кусочные', степень выраженности",
 "'Промахивающиеся', степень выраженности",
 'Аккуратность рисунка',
 'Штриховка',
 'Нажим штриховки (без особенностей)',
 'Нажим штриховки (слабый)',
 'Нажим штриховки (сильный)',
 'Нажим штриховки (варьирует)',
 'Аккуратность штриховки (низкая)',
 'Аккуратность штриховки (средняя (стандарт))',
 'Детализированность',
 'Стирания, исправления',
 'Устойчивость изображенного человека',
 'Грубые нарушения рисунка (отсутствуют)',
 'Грубые нарушения рисунка (отклонение от вертикали)',
 'Грубые нарушения рисунка (нарушение пропорций)',
 'Изображение в рамке',
 'Голова (без особенностей)',
 'Голова (искажена форма)',
 'Детали (лицо) (глаза (один или оба))',
 'Детали (лицо) (нос)',
 'Детали (лицо) (рот)',
 'Детали (лицо) (уши)',
 'Детали (лицо) (лоб)',
 'Детали (лицо) (волосы (шапка))',
 'Детали (лицо) (другое)',
 'Два глаза одинаковые',
 'Форма глаз (точка)',
 'Форма глаз (черточка)',
 'Форма глаз (круг)',
 'Форма глаз (овал, реалистичная форма)',
 "Форма глаз ('мультяшные')",
 'Размер глаз',
 'Дополнительные особенности глаз (без особенностей)',
 'Дополнительные особенности глаз (подчеркнутый контур)',
 "Дополнительные особенности глаз ('пустые')",
 'Дополнительные особенности глаз (зачернена радужка или весь глаз)',
 'Дополнительные особенности глаз (закрыты)',
 'Ресницы',
 'Нос (без особенностей)',
 'Нос (увеличен размер)',
 'Нос (усилен нажим)',
 'Рот',
 'Форма рта',
 'Положение рта / губ',
 'Зубы',
 'Язык',
 'Уши (без особенностей)',
 'Уши (преувеличен размер)',
 'Лоб (скрыт волосами или шапкой)',
 'Волосы или шапка (без особенностей)',
 'Дополнительные детали на лице (брови)',
 'Дополнительные детали на лице (усы и / или борода)',
 'Дополнительные детали на лице (другое)',
 'Дополнительные детали на лице (отсутствуют)',
 'Руки (одна или обе)',
 'Положение рук (слегка отставлены (стандарт))',
 'Положение рук (прижаты к телу (от верха до локтя))',
 'Положение рук (свободно опущены)',
 'Положение рук (сильно отставлены)',
 'Положение рук (вытянуты в стороны или вперед)',
 'Положение рук (подняты)',
 'Положение рук (дополнительно)',
 'Положение рук (за спиной или в карманах)',
 'Кисть (маленькая)',
 'Кисть (средняя (стандарт))',
 'Кисть (большая)',
 'Кисть (отсутствует)',
 'Ладонь, пальцы (изображены пальцы)',
 'Ладонь, пальцы (изображена ладонь)',
 "Ладонь, пальцы (положение 'варежки')",
 'Ладонь, пальцы (отсутствуют)',
 'Пальцы (изображены черточками)',
 'Пальцы (передана толщина)',
 'Ступни (без особенностей)',
 'Ступни (зачернены)',
 'Ступни (отсутствуют)',
 'Шея (без особенностей)',
 'Шея (короткая)',
 'Шея (длинная)',
 'Шея (отсутствует)',
 'Тело (округлое)',
 'Тело (прямоугольное)',
 'Тело (реалистичное)',
 'Тело (вытянутое)',
 'Тело (широкое)',
 'Тело (треугольное)',
 'Пол (женский)',
 'Пол (мужской)',
 'Пол (неопределенный)',
 'Пол (признаки пола подчеркнуты)',
 'Пол (подчеркнута генитальная область)',
 'Одежда (реалистичное изображение)',
 'Одежда (условное изображение)',
 "Одежда ('рентгеновский' рисунок)",
 'Одежда (отсутствует, тело изображено условно)',
 'Дополнительные детали изображения фигуры (отсутствуют)',
 'Дополнительные детали изображения фигуры (пуговицы)',
 'Дополнительные детали изображения фигуры (пуп)',
 'Дополнительные детали изображения фигуры (украшения)',
 'Дополнительные детали изображения фигуры (другое)',
 'Дополнительные детали изображения фигуры (ремень / пояс)',
 'Пуговицы',
 'Украшения, узор на одежде',
 'Дополнительно (в руке или рядом) (дополнительные предметы отсутствуют)',
 'Фон (отсутствует)',
 'Фон (опорная линия)',
 'Фон (солнце)',
 'Фон (земля)',
 'Шея отделена от тела линией',
 'Голова (размер)',
 'Лоб (размер)',
 'Волосы или шапка (аккуратность)',
 'Ноги (одна или обе) (положение)',
 'Ноги (постановка)',
 'Ноги (длина)',
 'Ступни (размер)',
 'Шея (размер)']

In [19]:
features_for_vlm = [
    # "Код-идентификатор обследуемого",
    
    # ----- 1 -----
    # "Возраст обследуемого",
    # "Пол обследуемого",
    # "Расположение на листе (без особенностей)",
    # "Расположение на листе (смещение вправо)",

    # "Расположение на листе (смещение влево)",
    # "Расположение на листе (смещение вверх)",
    # "Расположение на листе (смещение вниз)",
    # "Расположение на листе (размещение в углу)",

    # "Расположение на листе (изображение обрезано - есть место для дорисовки, но не дорисовано)",
    # "Расположение на листе (изоброжение обрезано - обрезан краем листа / нет места для дорисовки)",
    # "Степень смещения вправо",
    # "Степень смещения влево",

    # "Степень смещения вверх",
    # "Степень смещения вниз",
    # "Размещение в углу",
    # "Что обрезано (голова)",

    # ----- 2 -----
    # "Что обрезано (одна рука)",
    # "Что обрезано (обе руки)",
    # "Что обрезано (ноги)",
    "Размер рисунка",

    # "Ракурс",
    # "Поза",
    # "Фигура в движении",
    "Способ изображения",

    # "Изображение персонажа",
    # "Персонаж",
    # "Нажим (без особенностей)",
    # "Нажим (слабый)",

    # "Нажим (сильный)",  
    # "Нажим (сильно варьирует)",
    # "Особенности линии (без особенностей)",
    # "Особенности линии (множественные)",

    # ----- 3 -----
    # "Особенности линии (эскизные)",
    # "Особенности линии ('кусочные')",
    # "Особенности линии (недоведенные)",
    # "Особенности линии ('промахивающиеся')",

    # "Особенности линии (другое)",
    # "Множественные, степень выраженности",
    # "Эскизные, степень выраженности",
    # "'Кусочные', степень выраженности",

    # "Недоведенные, степень выраженности",
    # "'Промахивающиеся', степень выраженности",
    "Аккуратность рисунка",
    "Штриховка",

    # "Нажим штриховки (без особенностей)",
    # "Нажим штриховки (слабый)",
    # "Нажим штриховки (сильный)",
    # "Нажим штриховки (варьирует)",

    # ----- 4 -----
    # "Аккуратность штриховки (очень низкая)",
    # "Аккуратность штриховки (низкая)",
    # "Аккуратность штриховки (средняя (стандарт))",
    # "Аккуратность штриховки (высокая)",

    # "Аккуратность штриховки (очень высокая)",
    # "Аккуратность штриховки (разные виды штриховок)",
    "Детализированность",
    "Стирания, исправления",

    "Устойчивость изображенного человека",
    # "Грубые нарушения рисунка (отсутствуют)",
    # "Грубые нарушения рисунка (отклонение от вертикали)",
    # "Грубые нарушения рисунка (нарушение пропорций)",

    # "Грубые нарушения рисунка (грубая асимметрия)",
    # "Изображение в рамке",
    # "Голова (без особенностей)",
    "Голова (маленькая)",

    # ----- 5 -----
    "Голова (большая)",
    # "Голова (искажена форма)",
    # "Голова (зачерненная / заштрихованная)",
    # "Голова (отсутствует)",

    # "Детали (лицо) (глаза (один или оба))",
    # "Детали (лицо) (нос)",
    # "Детали (лицо) (рот)",
    # "Детали (лицо) (уши)",

    # "Детали (лицо) (лоб)",
    # "Детали (лицо) (волосы (шапка))",
    # "Детали (лицо) (другое)",
    # "Детали (лицо) (отсутствуют все указанные выше пункты)",

    # "Два глаза одинаковые",
    # "Форма глаз (точка)",
    # "Форма глаз (черточка)",
    # "Форма глаз (круг)",

    # ----- 6 -----
    # "Форма глаз (овал, реалистичная форма)",
    # "Форма глаз ('мультяшные')",
    # "Форма глаз (форма искажена)",
    # "Форма глаз (отсутствуют)",
    
    # "Форма левого глаза (точка)",
    # "Форма левого глаза (черточка)",
    # "Форма левого глаза (круг)",
    # "Форма левого глаза (овал, реалистичная форма)",

    # "Форма левого глаза ('мультяшные')",
    # "Форма левого глаза (форма искажена)",
    # "Форма левого глаза (отсутствует)",
    # "Форма правого глаза (точка)",

    # "Форма правого глаза (черточка)",
    # "Форма правого глаза (круг)",
    # "Форма правого глаза (овал, реалистичная форма)",
    # "Форма правого глаза ('мультяшные')",

    # ----- 7 -----
    # "Форма правого глаза (форма искажена)",
    # "Форма правого глаза (отсутствует)",
    # "Размер глаз",
    # "Размер левого глаза",

    # "Размер правого глаза",
    # "Дополнительные особенности глаз (без особенностей)",
    # "Дополнительные особенности глаз (подчеркнутый контур)",
    # "Дополнительные особенности глаз ('пустые')",

    # "Дополнительные особенности глаз (зачернена радужка или весь глаз)",
    # "Дополнительные особенности глаз (один или оба глаза закрыты волосами или шапкой)",
    # "Дополнительные особенности глаз (изображены очки (прозрачные))",
    # "Дополнительные особенности глаз (изображены темные очки)",

    # "Дополнительные особенности глаз (закрыты)",
    # "Дополнительные особенности глаз (полузакрыты (прищур))",
    # "Дополнительные особенности правого глаза (без особенностей)",
    # "Дополнительные особенности правого глаза (подчеркнутый контур)",

    # ----- 8 -----
    # "Дополнительные особенности правого глаза ('пустые')",
    # "Дополнительные особенности правого глаза (зачернена радужка или весь глаз)",
    # "Дополнительные особенности правого глаза (закрыт волосами или шапкой)",
    # "Дополнительные особенности правого глаза (изображены очки (прозрачные))",

    # "Дополнительные особенности правого глаза (закрыт)",
    # "Дополнительные особенности правого глаза (полузакрыт (прищур))",
    # "Дополнительные особенности левого глаза (без особенностей)",
    # "Дополнительные особенности левого глаза (подчеркнутый контур)",

    # "Дополнительные особенности левого глаза ('пустые')",
    # "Дополнительные особенности левого глаза (зачернена радужка или весь глаз)",
    # "Дополнительные особенности левого глаза (закрыт волосами или шапкой)",
    # "Дополнительные особенности левого глаза (изображены очки (прозрачные))",

    # "Дополнительные особенности левого глаза (изображены темные очки)",
    # "Дополнительные особенности левого глаза (закрыт)",
    # "Дополнительные особенности левого глаза (полузакрыт (прищур))",
    "Ресницы",

    # ----- 9 -----
    # "Нос (без особенностей)",
    # "Нос (увеличен размер)",
    # "Нос (усилен нажим)",
    # "Нос (другое)",
    
    # "Нос (отсутствует)",
    # "Рот",
    # "Форма рта",
    # "Положение рта / губ",

    "Зубы",
    # "Язык",
    # "Уши (без особенностей)",
    # "Уши (усилен нажим)",

    # "Уши (преувеличен размер)",
    # "Уши (другое)",
    # "Уши (отсутствуют)",
    # "Лоб (маленький)",

    # ----- 10 -----
    # "Лоб (средний (стандарт))",
    # "Лоб (большой)",
    # "Лоб (скрыт волосами или шапкой)",
    # "Лоб (скрыт волосами, усилен нажим)",

    # "Лоб (другое)",
    # "Лоб (отсутствует)",
    # "Волосы или шапка (без особенностей)",
    # "Волосы или шапка (нарисованы небрежно)",

    # "Волосы или шапка (нарисованы особо старательно)",
    # "Волосы или шапка (другое)",
    # "Волосы или шапка (отсутствуют)",
    "Дополнительные детали на лице (брови)",

    "Дополнительные детали на лице (усы и / или борода)",
    # "Дополнительные детали на лице (морщины)",
    # "Дополнительные детали на лице (маска)",
    # "Дополнительные детали на лице (рисунки на лице)",

    # ----- 11 -----
    # "Дополнительные детали на лице (другое)",
    # "Дополнительные детали на лице (отсутствуют)",
    # "Руки (одна или обе)",
    # "Положение рук (слегка отставлены (стандарт))",

    # "Положение рук (прижаты к телу (от верха до локтя))",
    # "Положение рук (свободно опущены)",
    # "Положение рук (сильно отставлены)",
    # "Положение рук (вытянуты в стороны или вперед)",

    "Положение рук (подняты)",
    # "Положение рук (дополнительно)",
    "Положение рук (за спиной или в карманах)",
    # "Положение рук (на фоне тела)",

    # "Положение рук (скрещены на груди)",
    # "Положение рук (уперты в бока)",
    # "Положение рук (закрывают генитальную область)",
    # "Положение рук (прижаты к голове)",

    # ----- 12 -----
    # "Положение рук (другое)",
    # "Положение правой руки",
    # "Положение правой руки.1",
    # "Положение левой руки",

    # "Положение левой руки.1",
    # "Положение руки (слегка отставлена (стандарт))",
    # "Положение руки (прижата к телу (от верха до локтя))",
    # "Положение руки (свободно опущена)",

    # "Положение руки (сильно отставлена)",
    # "Положение руки (вытянута в сторону или вперед)",
    # "Положение руки (поднята)",
    # "Положение руки (дополнительно)",

    # "Положение руки (за спиной или в кармане)",
    # "Положение руки (на фоне тела)",
    # "Положение руки (уперта в бок)",
    # "Положение руки (другое)",

    # ----- 13 -----
    # "Кисть (маленькая)",
    # "Кисть (средняя (стандарт))",
    # "Кисть (большая)",
    # "Кисть (повышен нажим)",

    # "Кисть (зачернена)",
    # "Кисть (отсутствует)",
    # "Ладонь, пальцы (изображены пальцы)",
    # "Ладонь, пальцы (изображена ладонь)",

    # "Ладонь, пальцы (положение 'варежки')",
    # "Ладонь, пальцы (кулак, большой палец снаружи)",
    # "Ладонь, пальцы (кулак, большой палец не виден)",
    # "Ладонь, пальцы (отсутствуют)",

    # "Пальцы (изображены черточками)",
    # "Пальцы (передана толщина)",
    # "Пальцы (округлые ногти)",
    # "Пальцы (заостренные ногти)",

    # ----- 14 -----
    # "Пальцы (другое)",
    # "Ноги (одна или обе) (две ноги в одинаковом положении)",
    # "Ноги (одна или обе) (две ноги в разном положении)",
    # "Ноги (одна или обе) (только одна нога)",

    # "Ноги (одна или обе) (скрыты препятствием)",
    # "Ноги (одна или обе) (отсутствуют)",
    # "Ноги (сведены вместе)",
    # "Ноги (слегка расставлены (стандарт))",

    # "Ноги (широко расставлены)",
    # "Ноги (короткие)",
    # "Ноги (длинные)",
    # "Ноги (другое)",

    # "Правая нога (вертикальна)",
    # "Правая нога (отставлена (стандарт))",
    # "Правая нога (согнута)",
    # "Правая нога (короткая)",

    # ----- 15 -----
    # "Правая нога (длинная)",
    # "Правая нога (другое)",
    # "Левая нога (вертикальна)",
    # "Левая нога (отставлена (стандарт))",

    # "Левая нога (согнута)",
    # "Левая нога (короткая)",
    # "Левая нога (длинная)",
    # "Левая нога (другое)",

    # "Нога (вертикальна)",
    # "Нога (другое)",
    # "Ступни (без особенностей)",
    # "Ступни (маленькие)",

    # "Ступни (большие)",
    # "Ступни (повышен нажим)",
    # "Ступни (зачернены)",
    # "Ступни (отсутствуют)",

    # ----- 16 -----
    # "Ступни (другое)",
    # "Шея (без особенностей)",
    # "Шея (одинарная линия)",
    # "Шея (тонкая)",

    # "Шея (толстая)",
    # "Шея (короткая)",
    # "Шея (длинная)",
    # "Шея (отсутствует)",

    # "Тело (палочка)",
    # "Тело (округлое)",
    # "Тело (прямоугольное)",
    # "Тело (реалистичное)",

    # "Тело (вытянутое)",
    # "Тело (широкое)",
    # "Тело (отсутствует)",
    # "Тело (треугольное)",

    # ----- 17 -----
    # "Тело (другое)",
    # "Пол (женский)",
    # "Пол (мужской)",
    # "Пол (неопределенный)",

    "Пол (признаки пола подчеркнуты)",
    # "Пол (подчеркнута генитальная область)",
    # "Пол (изображены половые органы)",
    "Одежда (реалистичное изображение)",

    # "Одежда (условное изображение)",
    # "Одежда ('рентгеновский' рисунок)",
    # "Одежда (отсутствует, тело изображено условно)",
    # "Одежда (отсутствует, человек обнажен)",

    # "Дополнительные детали изображения фигуры (отсутствуют)",
    # "Дополнительные детали изображения фигуры (пуговицы)",
    # "Дополнительные детали изображения фигуры (пуп)",
    # "Дополнительные детали изображения фигуры (ширинка)",

    # ----- 18 -----
    # "Дополнительные детали изображения фигуры (волосы на теле или конечностях)",
    # "Дополнительные детали изображения фигуры (украшения)",
    # "Дополнительные детали изображения фигуры (другое)",
    # "Дополнительные детали изображения фигуры (ремень / пояс)",
    
    # "Пуговицы",
    # "Украшения, узор на одежде",
    "Дополнительно (в руке или рядом) (игрушка, шарик)",
    # "Дополнительно (в руке или рядом) (цветок)",

    "Дополнительно (в руке или рядом) (животное)",
    # "Дополнительно (в руке или рядом) (палка)",
    "Дополнительно (в руке или рядом) (меч, нож, топор)",
    "Дополнительно (в руке или рядом) (пистолет, ружье)",

    # "Дополнительно (в руке или рядом) (шприц)",
    "Дополнительно (в руке или рядом) (сигарета)",
    # "Дополнительно (в руке или рядом) (сумка)",
    # "Дополнительно (в руке или рядом) (телефон)",

    # ----- 19 -----
    # "Дополнительно (в руке или рядом) (зонт)",
    # "Дополнительно (в руке или рядом) (дополнительные предметы отсутствуют)",
    # "Фон (отсутствует)",
    # "Фон (штриховка)",

    # "Фон (опорная линия)",
    # "Фон (заштрихованное облако)",
    # "Фон (пейзаж)",
    # "Фон (пейзаж преобладает над изображением человека)",

    # "Фон (дождь)",
    # "Фон (солнце)",
    # "Фон (земля)",
    # "Фон (другое)",

    # "Площадь штриховки",
    # "Нажим",
    # "Шея отделена от тела линией",
]

In [20]:
id_col = "Код-идентификатор обследуемого"
feat_cols = [c for c in features_for_vlm if c in df.columns and c != id_col]
df = df[[id_col] + feat_cols]
df

,Код-идентификатор обследуемого,Размер рисунка,Способ изображения,Аккуратность рисунка,Штриховка,Детализированность,"Стирания, исправления",Устойчивость изображенного человека,Ресницы,Зубы,Дополнительные детали на лице (брови),Дополнительные детали на лице (усы и / или борода),Положение рук (подняты),Положение рук (за спиной или в карманах),Пол (признаки пола подчеркнуты),Одежда (реалистичное изображение)
0,ЧУВ6лм1кл_6,стандарт,дифференцированная схема,низкая,нет,низкая,слабо выражены,относительно устойчив,нарисованы небрежно,отсутствуют,NaN,NaN,NaN,NaN,NaN,NaN
1,ЧУВ6лм1кл_5,стандарт,дифференцированная схема,средняя (стандарт),нет,средняя (стандарт),средняя выраженность,относительно устойчив,отсутствуют,отсутствуют,NaN,NaN,NaN,NaN,NaN,NaN
2,ЧУВ6лм1кл_4,стандарт,схема с элементами пластического,средняя (стандарт),нет,средняя (стандарт),слабо выражены,относительно устойчив,"имеются, без особенностей",отсутствуют,NaN,NaN,NaN,NaN,NaN,NaN
3,ЧУВ5лмдс_51,мелкий,примитивная схема,низкая,нет,низкая,отсутствуют,'висит в воздухе',отсутствуют,отсутствуют,брови,NaN,NaN,NaN,NaN,NaN
4,ЧУВ5лмдс_50,стандарт,дифференцированная схема,низкая,нет,низкая,сильно выражены,'висит в воздухе',отсутствуют,отсутствуют,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8425,ЧУВ5лждс (79),стандарт,дифференцированная схема,средняя (стандарт),нет,высокая,отсутствуют,вполне устойчив,отсутствуют,отсутствуют,NaN,NaN,NaN,NaN,NaN,NaN
8426,ЧУВ5лждс (78),стандарт,дифференцированная схема,высокая,нет,высокая,отсутствуют,относительно устойчив,"имеются, без особенностей",отсутствуют,NaN,NaN,NaN,NaN,NaN,NaN
8427,ЧУВ5лждс (77),стандарт,примитивная схема,низкая,нет,низкая,средняя выраженность,вполне устойчив,отсутствуют,отсутствуют,брови,NaN,подняты,NaN,NaN,NaN
8428,ЧУВ5лждс (76),стандарт,дифференцированная схема,средняя (стандарт),нет,средняя (стандарт),отсутствуют,относительно устойчив,"имеются, без особенностей",отсутствуют,брови,NaN,NaN,NaN,NaN,NaN
8429,ЧУВ5лждс (75),крупный,дифференцированная схема,средняя (стандарт),нет,низкая,отсутствуют,относительно устойчив,отсутствуют,отсутствуют,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
statistics = []

for col_idx in range(1, len(df.columns)):
    col_name = df.columns[col_idx]
    column_data = df[col_name]
    
    missing_count = int(column_data.isna().sum())
    
    value_counts = column_data.value_counts(dropna=False)
    
    stat_row = {
        'features': col_name,
        'unique_values': [],
        'frequencies': [],
        'missing_values': missing_count
    }
    
    has_empty = False
    for value, count in value_counts.items():
        value_str = str(value)
        if pd.isna(value) or value_str.lower() == 'nan':
            value_str = 'пусто'
            has_empty = True
        stat_row['unique_values'].append(value_str)
        stat_row['frequencies'].append(int(count))

    if missing_count > 0 and not has_empty:
        stat_row['unique_values'].append('пусто')
        stat_row['frequencies'].append(missing_count)

    statistics.append(stat_row)

In [22]:
prefix = "5_1"

In [23]:
analysis_dir = f"./{prefix}_analysis"
os.makedirs(analysis_dir, exist_ok=True)

output_file = f"{analysis_dir}/{prefix}_statistics_analysis.xlsx"

max_unique_values = max(len(stat['unique_values']) for stat in statistics)

wb = Workbook()
ws = wb.active
ws.title = "Статистика признаков"

headers = ['Признак']
for i in range(max_unique_values):
    headers.append(f'Значение_{i+1}')
    headers.append(f'Частота_{i+1}')
headers.append('Пропуски')

cell_font = Font(bold=False)
cell_align = Alignment(horizontal='left', vertical='center')

for col_idx, header in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col_idx, value=header)
    cell.font = cell_font
    cell.alignment = cell_align

for row_idx, stat in enumerate(statistics, 2):
    col_idx = 1
    
    c = ws.cell(row=row_idx, column=col_idx, value=stat['features'])
    c.font = cell_font
    c.alignment = cell_align
    col_idx += 1
    
    unique_values = stat['unique_values']
    frequencies = stat['frequencies']
    
    for i in range(max_unique_values):
        if i < len(unique_values):
            uv = unique_values[i]
            if isinstance(uv, str) and uv != 'пусто':
                try:
                    f = float(uv)
                    if f.is_integer():
                        uv = int(f)
                except ValueError:
                    pass
            c = ws.cell(row=row_idx, column=col_idx, value=uv)
            c.font = cell_font
            c.alignment = cell_align
            col_idx += 1
            c = ws.cell(row=row_idx, column=col_idx, value=int(frequencies[i]))
            c.font = cell_font
            c.alignment = cell_align
            col_idx += 1
        else:
            col_idx += 2
    
    c = ws.cell(row=row_idx, column=col_idx, value=int(stat['missing_values']))
    c.font = cell_font
    c.alignment = cell_align

for col in ws.columns:
    max_length = 0
    col_letter = col[0].column_letter
    for cell in col:
        try:
            if cell.value:
                max_length = max(max_length, len(str(cell.value)))
        except:
            pass
    adjusted_width = min(max_length + 2, 50)
    ws.column_dimensions[col_letter].width = adjusted_width

wb.save(output_file)

In [24]:
reports_dir = os.path.join(analysis_dir, f"{prefix}_reports")
os.makedirs(reports_dir, exist_ok=True)

output_file = f"{reports_dir}/{prefix}_statistics_analysis.xlsx"

plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

rows_per_page = 4
cols_per_page = 4
graphs_per_page = rows_per_page * cols_per_page

total_features = len(statistics)
num_pages = math.ceil(total_features / graphs_per_page)

for page in range(num_pages):
    start_idx = page * graphs_per_page
    end_idx = min(start_idx + graphs_per_page, total_features)
    page_features = statistics[start_idx:end_idx]
    
    fig, axes = plt.subplots(rows_per_page, cols_per_page, figsize=(20, 16))
    axes = axes.flatten() if rows_per_page > 1 else [axes] if cols_per_page == 1 else axes
    
    for idx, stat in enumerate(page_features):
        ax = axes[idx]
        
        feature_name = stat['features']; # print(feature_name)
        values = stat['unique_values']; # print(values)
        counts = stat['frequencies']; # print(counts)
        
        if len(values) > 0:
            empty_color = '#CCCCCC'
            non_empty_values = [v for v in values if str(v).lower() != 'пусто']
            num_non_empty = len(non_empty_values)
            
            colors = []
            palette = sns.color_palette("husl", max(num_non_empty, 1))
            palette_idx = 0
            
            for v in values:
                if str(v).lower() == 'пусто':
                    colors.append(empty_color)
                else:
                    colors.append(palette[palette_idx % len(palette)])
                    palette_idx += 1
            
            bars = ax.bar(range(len(values)), counts, 
                         color=colors, 
                         alpha=0.7, edgecolor='black')
            
            ax.set_xticks(range(len(values)))
            labels = []
            for v in values:
                v_str = str(v)
                if v_str.lower() in ['nan', 'missing']:
                    v_str = 'пусто'
                labels.append(v_str[:25] + '...' if len(v_str) > 25 else v_str)
            ax.set_xticklabels(labels, rotation=45, ha='right', fontsize=8)
            ax.set_ylabel('Частота', fontsize=10)
            
            title = feature_name[:70] + '...' if len(feature_name) > 70 else feature_name
            ax.set_title(title, fontsize=9, fontweight='bold', pad=5)
            
            ax.grid(True, alpha=0.3, axis='y')
            
            for i, count in enumerate(counts):
                ax.text(i, count, str(count), ha='center', va='bottom', fontsize=7)
        else:
            ax.text(0.5, 0.5, 'Нет данных', ha='center', va='center', 
                   transform=ax.transAxes, fontsize=12)
            ax.set_title(feature_name[:70] + '...' if len(feature_name) > 70 else feature_name, 
                        fontsize=9, fontweight='bold')
            ax.axis('off')
    
    for idx in range(len(page_features), graphs_per_page):
        axes[idx].axis('off')
    
    plt.suptitle(f'Страница {page + 1} из {num_pages}', 
                 fontsize=16, fontweight='bold', y=0.995)
    plt.tight_layout(rect=[0, 0, 1, 0.99])
    
    output_file = f"{reports_dir}/{prefix}_all_feats_distrs_{page + 1}.png"
    plt.savefig(output_file, dpi=200, bbox_inches='tight')
    plt.close()
    
    print(output_file)

./5_1_analysis\5_1_reports/5_1_all_feats_distrs_1.png

In [25]:
df.to_excel("5_1_features_for_vlm.xlsx", index=False)

In [26]:
import json
import pandas as pd

stats_path = "./5_1_analysis/5_1_statistics_analysis.xlsx"
stats_df = pd.read_excel(stats_path)

feature_col = "Признак" if "Признак" in stats_df.columns else stats_df.columns[0]
value_cols = [c for c in stats_df.columns if str(c).startswith("Значение_")]
value_cols = sorted(value_cols, key=lambda x: int(str(x).split("_")[-1]))

required = []
properties = {}

for _, row in stats_df.iterrows():
    feature_name_raw = row.get(feature_col)
    if pd.isna(feature_name_raw):
        continue

    feature_name = str(feature_name_raw).strip()
    if not feature_name:
        continue

    enum_values = []
    for col in value_cols:
        val = row.get(col)
        if pd.isna(val):
            continue

        val_str = str(val).strip()

        # В статистике пропуски маркируются как "пусто" —
        # для response format переводим в пустую строку.
        if val_str.lower() == "пусто":
            val_str = ""

        if val_str not in enum_values:
            enum_values.append(val_str)

    if not enum_values:
        enum_values = [""]

    required.append(feature_name)
    properties[feature_name] = {
        "type": "string",
        "enum": enum_values,
        "description": f"Категориальный признак: {feature_name}"
    }

response_format = {
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "required": required,
        "properties": properties
    }
}

print(json.dumps(response_format, ensure_ascii=False, indent=2))

{
  "schema": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "Размер рисунка",
      "Способ изображения",
      "Аккуратность рисунка",
      "Штриховка",
      "Детализированность",
      "Стирания, исправления",
      "Устойчивость изображенного человека",
      "Ресницы",
      "Зубы",
      "Дополнительные детали на лице (брови)",
      "Дополнительные детали на лице (усы и / или борода)",
      "Положение рук (подняты)",
      "Положение рук (за спиной или в карманах)",
      "Пол (признаки пола подчеркнуты)",
      "Одежда (реалистичное изображение)"
    ],
    "properties": {
      "Размер рисунка": {
        "type": "string",
        "enum": [
          "крупный",
          "стандарт",
          "мелкий"
        ],
        "description": "Категориальный признак: Размер рисунка"
      },
      "Способ изображения": {
        "type": "string",
        "enum": [
          "дифференцированная схема",
          "пластический",
          "промежуточный",
          "пластический с элементами схемы",
          "примитивная схема",
          "схема с элементами пластического",
          "условное изображение"
        ],
        "description": "Категориальный признак: Способ изображения"
      },
      "Аккуратность рисунка": {
        "type": "string",
        "enum": [
          "средняя (стандарт)",
          "низкая",
          "высокая"
        ],
        "description": "Категориальный признак: Аккуратность рисунка"
      },
      "Штриховка": {
        "type": "string",
        "enum": [
          "нет",
          "есть"
        ],
        "description": "Категориальный признак: Штриховка"
      },
      "Детализированность": {
        "type": "string",
        "enum": [
          "средняя (стандарт)",
          "низкая",
          "высокая"
        ],
        "description": "Категориальный признак: Детализированность"
      },
      "Стирания, исправления": {
        "type": "string",
        "enum": [
          "отсутствуют",
          "слабо выражены",
          "средняя выраженность",
          "сильно выражены"
        ],
        "description": "Категориальный признак: Стирания, исправления"
      },
      "Устойчивость изображенного человека": {
        "type": "string",
        "enum": [
          "вполне устойчив",
          "относительно устойчив",
          "'висит в воздухе'",
          "неустойчив"
        ],
        "description": "Категориальный признак: Устойчивость изображенного человека"
      },
      "Ресницы": {
        "type": "string",
        "enum": [
          "отсутствуют",
          "имеются, без особенностей",
          "",
          "длинные, загнутые",
          "нарисованы небрежно",
          "другое"
        ],
        "description": "Категориальный признак: Ресницы"
      },
      "Зубы": {
        "type": "string",
        "enum": [
          "отсутствуют",
          "",
          "нарисованы, без особенностей",
          "в большом количестве",
          "острые",
          "другое",
          "выделены нажимом"
        ],
        "description": "Категориальный признак: Зубы"
      },
      "Дополнительные детали на лице (брови)": {
        "type": "string",
        "enum": [
          "",
          "брови"
        ],
        "description": "Категориальный признак: Дополнительные детали на лице (брови)"
      },
      "Дополнительные детали на лице (усы и / или борода)": {
        "type": "string",
        "enum": [
          "",
          "усы и / или борода"
        ],
        "description": "Категориальный признак: Дополнительные детали на лице (усы и / или борода)"
      },
      "Положение рук (подняты)": {
        "type": "string",
        "enum": [
          "",
          "подняты"
        ],
        "description": "Категориальный признак: Положение рук (подняты)"
      },
      "Положение рук (за спиной или в карманах)": {
        "type": "string",
        "enum": [
          "",
          "за спиной или в карманах"
        ],
        "description": "Категориальный признак: Положение рук (за спиной или в карманах)"
      },
      "Пол (признаки пола подчеркнуты)": {
        "type": "string",
        "enum": [
          "",
          "признаки пола подчеркнуты"
        ],
        "description": "Категориальный признак: Пол (признаки пола подчеркнуты)"
      },
      "Одежда (реалистичное изображение)": {
        "type": "string",
        "enum": [
          "",
          "реалистичное изображение"
        ],
        "description": "Категориальный признак: Одежда (реалистичное изображение)"
      }
    }
  }
}